"""
Drill deck data.
Each deck is a dict with:
  - name: display name
  - icon: emoji
  - description: short description
  - cards: list of {"q": question, "a": answer, "hint": optional hint}
"""

from presidents_deck import PRESIDENTS_DECK
from vice_presidents_deck import VICE_PRESIDENTS_DECK
from revolutionary_war_deck import REVOLUTIONARY_WAR_DECK
from civil_war_deck import CIVIL_WAR_DECK
from early_american_wars_deck import EARLY_AMERICAN_WARS_DECK
from pre20c_american_history_deck import PRE20C_AMERICAN_HISTORY_DECK
from wwi_deck import WWI_DECK
from wwii_deck import WWII_DECK
from vietnam_war_deck import VIETNAM_WAR_DECK
from modern_american_history_deck import MODERN_AMERICAN_HISTORY_DECK
from korean_war_deck import KOREAN_WAR_DECK
from cold_war_deck import COLD_WAR_DECK
from gulf_war_deck import GULF_WAR_DECK
from shakespeare_tragedies_deck import SHAKESPEARE_TRAGEDIES_DECK
from shakespeare_comedies_histories_deck import SHAKESPEARE_COMEDIES_HISTORIES_DECK

DRILL_DECKS = [

    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "US State Capitals",
        "icon": "🗺️",
        "description": "All 50 US state capitals",
        "cards": [
            {"q": "Capital of Alabama", "a": "Montgomery"},
            {"q": "Capital of Alaska", "a": "Juneau"},
            {"q": "Capital of Arizona", "a": "Phoenix"},
            {"q": "Capital of Arkansas", "a": "Little Rock"},
            {"q": "Capital of California", "a": "Sacramento"},
            {"q": "Capital of Colorado", "a": "Denver"},
            {"q": "Capital of Connecticut", "a": "Hartford"},
            {"q": "Capital of Delaware", "a": "Dover"},
            {"q": "Capital of Florida", "a": "Tallahassee"},
            {"q": "Capital of Georgia", "a": "Atlanta"},
            {"q": "Capital of Hawaii", "a": "Honolulu"},
            {"q": "Capital of Idaho", "a": "Boise"},
            {"q": "Capital of Illinois", "a": "Springfield"},
            {"q": "Capital of Indiana", "a": "Indianapolis"},
            {"q": "Capital of Iowa", "a": "Des Moines"},
            {"q": "Capital of Kansas", "a": "Topeka"},
            {"q": "Capital of Kentucky", "a": "Frankfort"},
            {"q": "Capital of Louisiana", "a": "Baton Rouge"},
            {"q": "Capital of Maine", "a": "Augusta"},
            {"q": "Capital of Maryland", "a": "Annapolis"},
            {"q": "Capital of Massachusetts", "a": "Boston"},
            {"q": "Capital of Michigan", "a": "Lansing"},
            {"q": "Capital of Minnesota", "a": "Saint Paul"},
            {"q": "Capital of Mississippi", "a": "Jackson"},
            {"q": "Capital of Missouri", "a": "Jefferson City"},
            {"q": "Capital of Montana", "a": "Helena"},
            {"q": "Capital of Nebraska", "a": "Lincoln"},
            {"q": "Capital of Nevada", "a": "Carson City"},
            {"q": "Capital of New Hampshire", "a": "Concord"},
            {"q": "Capital of New Jersey", "a": "Trenton"},
            {"q": "Capital of New Mexico", "a": "Santa Fe"},
            {"q": "Capital of New York", "a": "Albany"},
            {"q": "Capital of North Carolina", "a": "Raleigh"},
            {"q": "Capital of North Dakota", "a": "Bismarck"},
            {"q": "Capital of Ohio", "a": "Columbus"},
            {"q": "Capital of Oklahoma", "a": "Oklahoma City"},
            {"q": "Capital of Oregon", "a": "Salem"},
            {"q": "Capital of Pennsylvania", "a": "Harrisburg"},
            {"q": "Capital of Rhode Island", "a": "Providence"},
            {"q": "Capital of South Carolina", "a": "Columbia"},
            {"q": "Capital of South Dakota", "a": "Pierre"},
            {"q": "Capital of Tennessee", "a": "Nashville"},
            {"q": "Capital of Texas", "a": "Austin"},
            {"q": "Capital of Utah", "a": "Salt Lake City"},
            {"q": "Capital of Vermont", "a": "Montpelier"},
            {"q": "Capital of Virginia", "a": "Richmond"},
            {"q": "Capital of Washington", "a": "Olympia"},
            {"q": "Capital of West Virginia", "a": "Charleston"},
            {"q": "Capital of Wisconsin", "a": "Madison"},
            {"q": "Capital of Wyoming", "a": "Cheyenne"},
        ]
    },

    PRESIDENTS_DECK,
    REVOLUTIONARY_WAR_DECK,
    CIVIL_WAR_DECK,

    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Chemical Elements",
        "icon": "⚗️",
        "description": "Elements, symbols, and atomic numbers",
        "cards": [
            {"q": "Symbol for Hydrogen", "a": "H", "hint": "Atomic number 1"},
            {"q": "Symbol for Helium", "a": "He", "hint": "Atomic number 2"},
            {"q": "Symbol for Lithium", "a": "Li", "hint": "Atomic number 3"},
            {"q": "Symbol for Carbon", "a": "C", "hint": "Atomic number 6"},
            {"q": "Symbol for Nitrogen", "a": "N", "hint": "Atomic number 7"},
            {"q": "Symbol for Oxygen", "a": "O", "hint": "Atomic number 8"},
            {"q": "Symbol for Sodium", "a": "Na", "hint": "From Latin 'Natrium'"},
            {"q": "Symbol for Magnesium", "a": "Mg", "hint": "Atomic number 12"},
            {"q": "Symbol for Aluminum", "a": "Al", "hint": "Atomic number 13"},
            {"q": "Symbol for Silicon", "a": "Si", "hint": "Atomic number 14"},
            {"q": "Symbol for Phosphorus", "a": "P", "hint": "Atomic number 15"},
            {"q": "Symbol for Sulfur", "a": "S", "hint": "Atomic number 16"},
            {"q": "Symbol for Chlorine", "a": "Cl", "hint": "Atomic number 17"},
            {"q": "Symbol for Potassium", "a": "K", "hint": "From Latin 'Kalium'"},
            {"q": "Symbol for Calcium", "a": "Ca", "hint": "Atomic number 20"},
            {"q": "Symbol for Iron", "a": "Fe", "hint": "From Latin 'Ferrum'"},
            {"q": "Symbol for Copper", "a": "Cu", "hint": "From Latin 'Cuprum'"},
            {"q": "Symbol for Zinc", "a": "Zn", "hint": "Atomic number 30"},
            {"q": "Symbol for Silver", "a": "Ag", "hint": "From Latin 'Argentum'"},
            {"q": "Symbol for Tin", "a": "Sn", "hint": "From Latin 'Stannum'"},
            {"q": "Symbol for Iodine", "a": "I", "hint": "Atomic number 53"},
            {"q": "Symbol for Gold", "a": "Au", "hint": "From Latin 'Aurum'"},
            {"q": "Symbol for Mercury", "a": "Hg", "hint": "From Latin 'Hydrargyrum'"},
            {"q": "Symbol for Lead", "a": "Pb", "hint": "From Latin 'Plumbum'"},
            {"q": "Symbol for Uranium", "a": "U", "hint": "Atomic number 92"},
            {"q": "What element has atomic number 1?", "a": "Hydrogen"},
            {"q": "What element has atomic number 2?", "a": "Helium"},
            {"q": "What element has atomic number 6?", "a": "Carbon"},
            {"q": "What element has atomic number 8?", "a": "Oxygen"},
            {"q": "What element has atomic number 26?", "a": "Iron"},
            {"q": "What element has atomic number 79?", "a": "Gold"},
            {"q": "What element has atomic number 92?", "a": "Uranium"},
            {"q": "Lightest element on the periodic table", "a": "Hydrogen"},
            {"q": "Most abundant element in the universe", "a": "Hydrogen"},
            {"q": "Most abundant element in Earth's crust", "a": "Oxygen"},
            {"q": "Element named after Marie Curie's homeland", "a": "Polonium"},
            {"q": "Only liquid metal at room temperature", "a": "Mercury"},
            {"q": "Hardest natural substance; form of carbon", "a": "Diamond (Carbon)"},
            {"q": "Element that makes up most of air (78%)", "a": "Nitrogen"},
            {"q": "Noble gas used in party balloons", "a": "Helium"},
            {"q": "Radioactive element discovered by Marie Curie", "a": "Radium"},
            {"q": "Element essential to all known life, basis of organic chemistry", "a": "Carbon"},
        ]
    },

    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Greek & Roman Gods",
        "icon": "⚡",
        "description": "Major deities of Greek and Roman mythology with their Roman/Greek equivalents",
        "cards": [
            {"q": "Greek god of the sky and thunder; king of the gods", "a": "Zeus", "hint": "Roman equivalent: Jupiter"},
            {"q": "Roman equivalent of Zeus", "a": "Jupiter"},
            {"q": "Greek goddess of marriage; Zeus's wife", "a": "Hera", "hint": "Roman equivalent: Juno"},
            {"q": "Roman equivalent of Hera", "a": "Juno"},
            {"q": "Greek god of the sea", "a": "Poseidon", "hint": "Roman equivalent: Neptune"},
            {"q": "Roman equivalent of Poseidon", "a": "Neptune"},
            {"q": "Greek god of the underworld", "a": "Hades", "hint": "Roman equivalent: Pluto"},
            {"q": "Roman equivalent of Hades", "a": "Pluto"},
            {"q": "Greek goddess of wisdom and warfare", "a": "Athena", "hint": "Roman equivalent: Minerva"},
            {"q": "Roman equivalent of Athena", "a": "Minerva"},
            {"q": "Greek god of the sun, music, and prophecy", "a": "Apollo", "hint": "Same name in Roman mythology"},
            {"q": "Greek goddess of the hunt and the moon", "a": "Artemis", "hint": "Roman equivalent: Diana"},
            {"q": "Roman equivalent of Artemis", "a": "Diana"},
            {"q": "Greek god of war", "a": "Ares", "hint": "Roman equivalent: Mars"},
            {"q": "Roman equivalent of Ares", "a": "Mars"},
            {"q": "Greek goddess of love and beauty", "a": "Aphrodite", "hint": "Roman equivalent: Venus"},
            {"q": "Roman equivalent of Aphrodite", "a": "Venus"},
            {"q": "Greek god of fire and the forge", "a": "Hephaestus", "hint": "Roman equivalent: Vulcan"},
            {"q": "Roman equivalent of Hephaestus", "a": "Vulcan"},
            {"q": "Greek messenger god; god of commerce and thieves", "a": "Hermes", "hint": "Roman equivalent: Mercury"},
            {"q": "Roman equivalent of Hermes", "a": "Mercury"},
            {"q": "Greek god of wine and festivity", "a": "Dionysus", "hint": "Roman equivalent: Bacchus"},
            {"q": "Roman equivalent of Dionysus", "a": "Bacchus"},
            {"q": "Greek goddess of the harvest and agriculture", "a": "Demeter", "hint": "Roman equivalent: Ceres"},
            {"q": "Roman equivalent of Demeter", "a": "Ceres"},
            {"q": "Greek goddess of the hearth and home", "a": "Hestia", "hint": "Roman equivalent: Vesta"},
            {"q": "Greek titan who held up the sky", "a": "Atlas"},
            {"q": "Greek titan who gave fire to humanity", "a": "Prometheus"},
            {"q": "Greek god of love (son of Aphrodite)", "a": "Eros", "hint": "Roman equivalent: Cupid"},
            {"q": "Roman equivalent of Eros", "a": "Cupid"},
            {"q": "Greek hero who completed twelve labors", "a": "Hercules (Heracles)"},
            {"q": "Greek hero of the Trojan War; his heel was his weakness", "a": "Achilles"},
            {"q": "Greek hero who blinded the Cyclops Polyphemus", "a": "Odysseus (Ulysses)"},
            {"q": "Three-headed dog guarding the entrance to the underworld", "a": "Cerberus"},
            {"q": "Winged horse of Greek mythology", "a": "Pegasus"},
            {"q": "Half-man, half-bull creature of Greek mythology", "a": "Minotaur"},
            {"q": "The Muses were goddesses of these nine arts — what were they associated with?", "a": "Arts and sciences (music, poetry, history, etc.)"},
            {"q": "River of forgetfulness in the Greek underworld", "a": "Lethe"},
            {"q": "Greek personification of death", "a": "Thanatos"},
            {"q": "The three Fates in Greek mythology collectively", "a": "Moirai (Clotho, Lachesis, Atropos)"},
        ]
    },

    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Shakespeare",
        "icon": "🎭",
        "description": "Plays, characters, quotes, and facts about Shakespeare",
        "cards": [
            {"q": "Shakespeare's birthplace", "a": "Stratford-upon-Avon"},
            {"q": "The theater most associated with Shakespeare in London", "a": "The Globe"},
            {"q": "Shakespeare's four great tragedies", "a": "Hamlet, Othello, Macbeth, King Lear"},
            {"q": "Number of sonnets Shakespeare wrote", "a": "154"},
            {"q": "Shakespeare's only son's name", "a": "Hamnet"},
        ]
    },

    # ── NEW EXPANDED SHAKESPEARE DECKS ──────────────────────────────────────
    SHAKESPEARE_TRAGEDIES_DECK,
    SHAKESPEARE_COMEDIES_HISTORIES_DECK,

    # ── NEW HISTORY & WAR DECKS ──────────────────────────────────────────────
    VICE_PRESIDENTS_DECK,
    EARLY_AMERICAN_WARS_DECK,
    PRE20C_AMERICAN_HISTORY_DECK,
    MODERN_AMERICAN_HISTORY_DECK,
    WWI_DECK,
    WWII_DECK,
    VIETNAM_WAR_DECK,
    KOREAN_WAR_DECK,
    COLD_WAR_DECK,
    GULF_WAR_DECK,

    # ── EXISTING EXTERNAL DECKS ───────────────────────────────────────────────

    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Books & Their Authors",
        "icon": "📚",
        "description": "Classic and notable works matched to their authors",
        "cards": [
            {"q": "Author of 'Pride and Prejudice'", "a": "Jane Austen"},
            {"q": "Author of 'Moby-Dick'", "a": "Herman Melville"},
            {"q": "Author of 'The Great Gatsby'", "a": "F. Scott Fitzgerald"},
            {"q": "Author of 'To Kill a Mockingbird'", "a": "Harper Lee"},
            {"q": "Author of '1984'", "a": "George Orwell"},
            {"q": "Author of 'Animal Farm'", "a": "George Orwell"},
            {"q": "Author of 'Brave New World'", "a": "Aldous Huxley"},
            {"q": "Author of 'The Catcher in the Rye'", "a": "J.D. Salinger"},
            {"q": "Author of 'Of Mice and Men'", "a": "John Steinbeck"},
            {"q": "Author of 'The Grapes of Wrath'", "a": "John Steinbeck"},
            {"q": "Author of 'Crime and Punishment'", "a": "Fyodor Dostoevsky"},
            {"q": "Author of 'The Brothers Karamazov'", "a": "Fyodor Dostoevsky"},
            {"q": "Author of 'War and Peace'", "a": "Leo Tolstoy"},
            {"q": "Author of 'Anna Karenina'", "a": "Leo Tolstoy"},
            {"q": "Author of 'One Hundred Years of Solitude'", "a": "Gabriel García Márquez"},
            {"q": "Author of 'Don Quixote'", "a": "Miguel de Cervantes"},
            {"q": "Author of 'The Odyssey'", "a": "Homer"},
            {"q": "Author of 'The Iliad'", "a": "Homer"},
            {"q": "Author of 'The Divine Comedy'", "a": "Dante Alighieri"},
            {"q": "Author of 'Hamlet'", "a": "William Shakespeare"},
            {"q": "Author of 'A Tale of Two Cities'", "a": "Charles Dickens"},
            {"q": "Author of 'Great Expectations'", "a": "Charles Dickens"},
            {"q": "Author of 'Jane Eyre'", "a": "Charlotte Brontë"},
            {"q": "Author of 'Wuthering Heights'", "a": "Emily Brontë"},
            {"q": "Author of 'The Adventures of Huckleberry Finn'", "a": "Mark Twain"},
            {"q": "Author of 'The Old Man and the Sea'", "a": "Ernest Hemingway"},
            {"q": "Author of 'Ulysses'", "a": "James Joyce"},
            {"q": "Author of 'Mrs Dalloway'", "a": "Virginia Woolf"},
            {"q": "Author of 'Invisible Man'", "a": "Ralph Ellison"},
            {"q": "Author of 'Beloved'", "a": "Toni Morrison"},
            {"q": "Author of 'The Handmaid's Tale'", "a": "Margaret Atwood"},
            {"q": "Author of 'Catch-22'", "a": "Joseph Heller"},
            {"q": "Author of 'Slaughterhouse-Five'", "a": "Kurt Vonnegut"},
            {"q": "Author of 'The Metamorphosis'", "a": "Franz Kafka"},
            {"q": "Author of 'The Trial'", "a": "Franz Kafka"},
            {"q": "Author of 'Lolita'", "a": "Vladimir Nabokov"},
            {"q": "Author of 'In Search of Lost Time'", "a": "Marcel Proust"},
            {"q": "Author of 'Middlemarch'", "a": "George Eliot"},
            {"q": "Author of 'Frankenstein'", "a": "Mary Shelley"},
            {"q": "Author of 'Dracula'", "a": "Bram Stoker"},
            {"q": "Author of 'The Picture of Dorian Gray'", "a": "Oscar Wilde"},
            {"q": "Author of 'Sherlock Holmes'", "a": "Arthur Conan Doyle"},
            {"q": "Author of 'On the Road'", "a": "Jack Kerouac"},
            {"q": "Author of 'The Sun Also Rises'", "a": "Ernest Hemingway"},
            {"q": "Author of 'East of Eden'", "a": "John Steinbeck"},
            {"q": "Author of 'The Sound and the Fury'", "a": "William Faulkner"},
            {"q": "Author of 'As I Lay Dying'", "a": "William Faulkner"},
            {"q": "Author of 'Leaves of Grass'", "a": "Walt Whitman"},
            {"q": "Author of 'The Waste Land'", "a": "T.S. Eliot"},
            {"q": "Author of 'Things Fall Apart'", "a": "Chinua Achebe"},
        ]
    },

    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Oscar Best Picture",
        "icon": "🏆",
        "description": "Academy Award Best Picture winners",
        "cards": [
            {"q": "Best Picture 1928 (first ever Oscar)", "a": "Wings"},
            {"q": "Best Picture 1939", "a": "Gone with the Wind"},
            {"q": "Best Picture 1942", "a": "Mrs. Miniver"},
            {"q": "Best Picture 1946", "a": "The Best Years of Our Lives"},
            {"q": "Best Picture 1950", "a": "All About Eve", "hint": "Nominated for 14 Oscars"},
            {"q": "Best Picture 1960", "a": "Ben-Hur", "hint": "Won 11 Oscars"},
            {"q": "Best Picture 1963", "a": "Lawrence of Arabia"},
            {"q": "Best Picture 1966", "a": "The Sound of Music"},
            {"q": "Best Picture 1968", "a": "In the Heat of the Night"},
            {"q": "Best Picture 1973", "a": "The Godfather"},
            {"q": "Best Picture 1975", "a": "The Godfather Part II"},
            {"q": "Best Picture 1976", "a": "One Flew Over the Cuckoo's Nest"},
            {"q": "Best Picture 1978", "a": "Annie Hall"},
            {"q": "Best Picture 1979", "a": "The Deer Hunter"},
            {"q": "Best Picture 1980", "a": "Kramer vs. Kramer"},
            {"q": "Best Picture 1982", "a": "Chariots of Fire"},
            {"q": "Best Picture 1983", "a": "Gandhi"},
            {"q": "Best Picture 1985", "a": "Amadeus"},
            {"q": "Best Picture 1986", "a": "Out of Africa"},
            {"q": "Best Picture 1988", "a": "The Last Emperor"},
            {"q": "Best Picture 1989", "a": "Rain Man"},
            {"q": "Best Picture 1990", "a": "Driving Miss Daisy"},
            {"q": "Best Picture 1991", "a": "Dances with Wolves"},
            {"q": "Best Picture 1992", "a": "The Silence of the Lambs"},
            {"q": "Best Picture 1993", "a": "Unforgiven"},
            {"q": "Best Picture 1994", "a": "Schindler's List"},
            {"q": "Best Picture 1995", "a": "Forrest Gump"},
            {"q": "Best Picture 1996", "a": "Braveheart"},
            {"q": "Best Picture 1997", "a": "The English Patient"},
            {"q": "Best Picture 1998", "a": "Titanic", "hint": "Won 11 Oscars"},
            {"q": "Best Picture 1999", "a": "Shakespeare in Love"},
            {"q": "Best Picture 2000", "a": "American Beauty"},
            {"q": "Best Picture 2001", "a": "Gladiator"},
            {"q": "Best Picture 2002", "a": "A Beautiful Mind"},
            {"q": "Best Picture 2003", "a": "Chicago"},
            {"q": "Best Picture 2004", "a": "The Lord of the Rings: The Return of the King"},
            {"q": "Best Picture 2005", "a": "Million Dollar Baby"},
            {"q": "Best Picture 2006", "a": "Crash"},
            {"q": "Best Picture 2007", "a": "The Departed"},
            {"q": "Best Picture 2008", "a": "No Country for Old Men"},
            {"q": "Best Picture 2009", "a": "Slumdog Millionaire"},
            {"q": "Best Picture 2010", "a": "The Hurt Locker"},
            {"q": "Best Picture 2011", "a": "The King's Speech"},
            {"q": "Best Picture 2012", "a": "The Artist"},
            {"q": "Best Picture 2013", "a": "Argo"},
            {"q": "Best Picture 2014", "a": "12 Years a Slave"},
            {"q": "Best Picture 2015", "a": "Birdman"},
            {"q": "Best Picture 2016", "a": "Spotlight"},
            {"q": "Best Picture 2017", "a": "Moonlight", "hint": "Famous envelope mix-up with La La Land"},
            {"q": "Best Picture 2018", "a": "The Shape of Water"},
            {"q": "Best Picture 2019", "a": "Green Book"},
            {"q": "Best Picture 2020", "a": "Parasite", "hint": "First non-English language film to win"},
            {"q": "Best Picture 2021", "a": "Nomadland"},
            {"q": "Best Picture 2022", "a": "CODA"},
            {"q": "Best Picture 2023", "a": "Everything Everywhere All at Once"},
            {"q": "Best Picture 2024", "a": "Oppenheimer"},
        ]
    },

    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Nobel Prize",
        "icon": "🎖️",
        "description": "Nobel Prize categories, history, and notable laureates",
        "cards": [
            {"q": "The six Nobel Prize categories", "a": "Physics, Chemistry, Physiology/Medicine, Literature, Peace, Economic Sciences"},
            {"q": "Nobel Prizes are awarded in this Swedish city (except Peace)", "a": "Stockholm"},
            {"q": "The Nobel Peace Prize is awarded in this city", "a": "Oslo"},
            {"q": "Alfred Nobel invented this explosive", "a": "Dynamite"},
            {"q": "Nobel Prizes have been awarded since this year", "a": "1901"},
            {"q": "First woman to win a Nobel Prize (and only person to win in two different sciences)", "a": "Marie Curie"},
            {"q": "Marie Curie's two Nobel Prizes were in these fields", "a": "Physics (1903) and Chemistry (1911)"},
            {"q": "Person who won the Nobel Peace Prize in 1964 for civil rights leadership", "a": "Martin Luther King Jr."},
            {"q": "Albert Einstein won the Nobel Prize in Physics for this discovery", "a": "The photoelectric effect (1921)"},
            {"q": "This organization has won the Nobel Peace Prize the most times", "a": "International Committee of the Red Cross (3 times)"},
            {"q": "First US President to win the Nobel Peace Prize while in office", "a": "Theodore Roosevelt (1906)"},
            {"q": "US President who won the Nobel Peace Prize in 2009", "a": "Barack Obama"},
            {"q": "Mother Teresa won the Nobel Peace Prize in this year", "a": "1979"},
            {"q": "Malala Yousafzai became the youngest Nobel laureate in this year", "a": "2014"},
            {"q": "Nelson Mandela won the Nobel Peace Prize in this year", "a": "1993"},
            {"q": "The Nobel Prize in Economic Sciences was first awarded in this decade", "a": "1969"},
            {"q": "William Faulkner, Ernest Hemingway, and Toni Morrison all won this Nobel category", "a": "Literature"},
            {"q": "The Nobel Prize amount is funded by Alfred Nobel's fortune from this invention", "a": "Dynamite"},
            {"q": "Watson and Crick won the Nobel Prize in this category for DNA structure", "a": "Physiology or Medicine (1962)"},
            {"q": "The IPCC (climate science group) shared the Nobel Peace Prize with this US politician in 2007", "a": "Al Gore"},
            {"q": "This prize, not a Nobel, is sometimes called the 'Nobel of Mathematics'", "a": "Fields Medal"},
            {"q": "Aung San Suu Kyi won the Nobel Peace Prize for her work in this country", "a": "Myanmar (Burma)"},
            {"q": "The Nobel Prize medal features the profile of this man", "a": "Alfred Nobel"},
            {"q": "Nobel laureates receive a medal, diploma, and this monetary award (approximate)", "a": "~10 million Swedish kronor (about $1 million USD)"},
            {"q": "Bob Dylan won the Nobel Prize in Literature in 2016 — he is known primarily as this", "a": "Singer-songwriter / musician"},
        ]
    },

    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Countries & Currencies",
        "icon": "🌍",
        "description": "Countries, their currencies, and capital cities",
        "cards": [
            {"q": "Currency of Japan", "a": "Yen"},
            {"q": "Currency of China", "a": "Yuan (Renminbi)"},
            {"q": "Currency of India", "a": "Rupee"},
            {"q": "Currency of Russia", "a": "Ruble"},
            {"q": "Currency of Brazil", "a": "Real"},
            {"q": "Currency of Mexico", "a": "Peso"},
            {"q": "Currency of South Korea", "a": "Won"},
            {"q": "Currency of Australia", "a": "Australian Dollar"},
            {"q": "Currency of Canada", "a": "Canadian Dollar"},
            {"q": "Currency of Switzerland", "a": "Swiss Franc"},
            {"q": "Currency of Sweden", "a": "Swedish Krona"},
            {"q": "Currency of Norway", "a": "Norwegian Krone"},
            {"q": "Currency of Denmark", "a": "Danish Krone"},
            {"q": "Currency of South Africa", "a": "Rand"},
            {"q": "Currency of Egypt", "a": "Egyptian Pound"},
            {"q": "Currency of Saudi Arabia", "a": "Riyal"},
            {"q": "Currency of Turkey", "a": "Lira"},
            {"q": "Currency of Israel", "a": "Shekel"},
            {"q": "Currency of Argentina", "a": "Peso"},
            {"q": "Currency of Nigeria", "a": "Naira"},
            {"q": "Capital of Australia", "a": "Canberra", "hint": "Not Sydney or Melbourne"},
            {"q": "Capital of Canada", "a": "Ottawa", "hint": "Not Toronto"},
            {"q": "Capital of Brazil", "a": "Brasília", "hint": "Not Rio de Janeiro or São Paulo"},
            {"q": "Capital of Australia", "a": "Canberra"},
            {"q": "Capital of New Zealand", "a": "Wellington", "hint": "Not Auckland"},
            {"q": "Capital of South Africa (seat of government)", "a": "Pretoria", "hint": "Has three capitals; Pretoria is executive"},
            {"q": "Capital of India", "a": "New Delhi"},
            {"q": "Capital of China", "a": "Beijing"},
            {"q": "Capital of Japan", "a": "Tokyo"},
            {"q": "Capital of Russia", "a": "Moscow"},
            {"q": "Capital of Germany", "a": "Berlin"},
            {"q": "Capital of France", "a": "Paris"},
            {"q": "Capital of Italy", "a": "Rome"},
            {"q": "Capital of Spain", "a": "Madrid"},
            {"q": "Capital of the Netherlands", "a": "Amsterdam", "hint": "Government is in The Hague"},
            {"q": "Capital of Switzerland", "a": "Bern", "hint": "Not Zurich or Geneva"},
            {"q": "Capital of Sweden", "a": "Stockholm"},
            {"q": "Capital of Argentina", "a": "Buenos Aires"},
            {"q": "Capital of Egypt", "a": "Cairo"},
            {"q": "Capital of Nigeria", "a": "Abuja", "hint": "Not Lagos"},
            {"q": "Capital of Kenya", "a": "Nairobi"},
            {"q": "Capital of Saudi Arabia", "a": "Riyadh"},
            {"q": "Capital of Pakistan", "a": "Islamabad", "hint": "Not Karachi or Lahore"},
            {"q": "Capital of Indonesia", "a": "Jakarta"},
            {"q": "Capital of Mexico", "a": "Mexico City"},
        ]
    },

    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Bible Books & Stories",
        "icon": "✝️",
        "description": "Books of the Bible, key stories, and figures",
        "cards": [
            {"q": "First book of the Old Testament", "a": "Genesis"},
            {"q": "Last book of the New Testament", "a": "Revelation"},
            {"q": "Shortest book of the Bible (by verse count)", "a": "3 John"},
            {"q": "Longest book of the Bible (by verse count)", "a": "Psalms"},
            {"q": "Number of books in the Old Testament (Protestant)", "a": "39"},
            {"q": "Number of books in the New Testament", "a": "27"},
            {"q": "Number of books in the entire Protestant Bible", "a": "66"},
            {"q": "The first four books of the New Testament", "a": "Matthew, Mark, Luke, John (the Gospels)"},
            {"q": "The first five books of the Bible (the Pentateuch)", "a": "Genesis, Exodus, Leviticus, Numbers, Deuteronomy"},
            {"q": "Book of the Bible containing the Ten Commandments (first giving)", "a": "Exodus"},
            {"q": "Garden where Adam and Eve lived", "a": "Eden"},
            {"q": "The ark builder in Genesis", "a": "Noah"},
            {"q": "Abraham was asked to sacrifice this son", "a": "Isaac"},
            {"q": "Jacob's twelve sons became the twelve of these", "a": "Tribes of Israel"},
            {"q": "The Hebrew prophet raised in Pharaoh's court who led the Exodus", "a": "Moses"},
            {"q": "The sea Moses parted in the Exodus", "a": "The Red Sea"},
            {"q": "God spoke to Moses from a burning of this", "a": "Bush (burning bush)"},
            {"q": "David killed this Philistine giant with a sling", "a": "Goliath"},
            {"q": "The wisest king of Israel, known for his judgments", "a": "Solomon"},
            {"q": "Solomon built this structure in Jerusalem", "a": "The Temple (First Temple)"},
            {"q": "Prophet who was swallowed by a great fish", "a": "Jonah"},
            {"q": "The Book of Job concerns this theme primarily", "a": "Suffering and faith"},
            {"q": "The Sermon on the Mount is found in this Gospel", "a": "Matthew"},
            {"q": "Jesus fed 5,000 people with these two items", "a": "Five loaves and two fish"},
            {"q": "The apostle who denied Jesus three times", "a": "Peter"},
            {"q": "The apostle who betrayed Jesus for 30 pieces of silver", "a": "Judas Iscariot"},
            {"q": "The disciple known as 'the beloved disciple'", "a": "John"},
            {"q": "Paul's letter to the Romans is found in this section of the Bible", "a": "The New Testament (Epistles)"},
            {"q": "The Book of Psalms is attributed primarily to this king", "a": "David"},
            {"q": "The Book of Proverbs is attributed primarily to this king", "a": "Solomon"},
            {"q": "The two cities destroyed by fire and brimstone in Genesis", "a": "Sodom and Gomorrah"},
            {"q": "Lot's wife turned into this when she looked back at Sodom", "a": "A pillar of salt"},
            {"q": "The river in which Jesus was baptized", "a": "The Jordan River"},
            {"q": "This Old Testament figure was known for his great strength", "a": "Samson"},
            {"q": "Samson's weakness was revealed through this woman", "a": "Delilah"},
        ]
    },

]
