"""
modern_american_history_deck.py
20th and 21st century American history — politics, economy, social movements,
culture, technology, and key events. Excludes WWI, WWII, Korea, Vietnam,
Gulf War, and post-9/11 wars (covered in separate decks).
"""

MODERN_AMERICAN_HISTORY_DECK = {
    "name": "20th & 21st Century American History",
    "icon": "🗽",
    "description": "Progressive Era through today — politics, civil rights, economy, culture, and key events",
    "cards": [

        # ── PROGRESSIVE ERA (1900–1920) ───────────────────────────────────────
        {"q": "President who launched the 'Square Deal' and busted trusts in the early 1900s", "a": "Theodore Roosevelt"},
        {"q": "TR used this law aggressively to break up Standard Oil and Northern Securities", "a": "Sherman Antitrust Act"},
        {"q": "The 1906 Pure Food and Drug Act was triggered by Upton Sinclair's novel about this industry", "a": "Meatpacking"},
        {"q": "TR's policy of government regulation to balance business, labor, and consumer interests", "a": "Square Deal"},
        {"q": "Constitutional amendment that established the federal income tax, ratified 1913", "a": "16th Amendment"},
        {"q": "Constitutional amendment that established direct election of US Senators, ratified 1913", "a": "17th Amendment"},
        {"q": "Constitutional amendment that prohibited alcohol, ratified 1919", "a": "18th Amendment (Prohibition)"},
        {"q": "Constitutional amendment that gave women the right to vote, ratified 1920", "a": "19th Amendment"},
        {"q": "Federal reserve system established in 1913 under this president", "a": "Woodrow Wilson"},
        {"q": "Wilson's domestic reform program was called this", "a": "New Freedom"},
        {"q": "The NAACP was founded in 1909 — what it stands for", "a": "National Association for the Advancement of Colored People"},
        {"q": "Black leader who co-founded the NAACP and edited its magazine The Crisis", "a": "W.E.B. Du Bois"},
        {"q": "Du Bois's concept that Black Americans should demand full civil rights immediately (vs Booker T. Washington's gradualism)", "a": "The Talented Tenth / immediate equality"},
        {"q": "The Triangle Shirtwaist Factory fire of 1911 killed 146 workers and led to sweeping reforms of these", "a": "Labor laws and fire safety regulations"},
        {"q": "The 1919 Red Scare led to mass deportations of suspected radicals under this attorney general", "a": "A. Mitchell Palmer (Palmer Raids)"},

        # ── ROARING TWENTIES & GREAT DEPRESSION ───────────────────────────────
        {"q": "The era of the 1920s known for jazz, flappers, and economic prosperity", "a": "Roaring Twenties (Jazz Age)"},
        {"q": "Constitutional amendment that repealed Prohibition, ratified 1933", "a": "21st Amendment"},
        {"q": "The illegal bars that sold alcohol during Prohibition", "a": "Speakeasies"},
        {"q": "Most famous gangster of the Prohibition era, based in Chicago", "a": "Al Capone"},
        {"q": "Al Capone was eventually convicted of this crime, not bootlegging", "a": "Tax evasion"},
        {"q": "The Great Migration brought approximately 6 million Black Americans from the South to Northern cities between 1910 and this decade", "a": "1970s (two waves: 1910–1940 and 1940–1970)"},
        {"q": "Harlem Renaissance was a flowering of Black artistic and cultural life centered in this New York neighborhood", "a": "Harlem"},
        {"q": "Famous Harlem Renaissance poet known for 'A Dream Deferred'", "a": "Langston Hughes"},
        {"q": "The stock market crash that began the Great Depression occurred on this date", "a": "October 29, 1929 (Black Tuesday)"},
        {"q": "President blamed for the Great Depression, whose name was mockingly applied to shantytowns", "a": "Herbert Hoover"},
        {"q": "Shantytowns of homeless people during the Depression were called this", "a": "Hoovervilles"},
        {"q": "The Dust Bowl of the 1930s devastated this region of the country", "a": "Great Plains (Oklahoma, Texas, Kansas, Colorado)"},
        {"q": "John Steinbeck's novel about Dust Bowl migrants traveling to California", "a": "The Grapes of Wrath"},
        {"q": "FDR's first act as president was to declare a national bank holiday — he explained it to the public via these radio addresses", "a": "Fireside chats"},
        {"q": "FDR's New Deal agency that employed young men in conservation work", "a": "Civilian Conservation Corps (CCC)"},
        {"q": "New Deal agency that employed artists, writers, and workers on public projects", "a": "Works Progress Administration (WPA)"},
        {"q": "New Deal agency that regulated the securities industry after the crash", "a": "Securities and Exchange Commission (SEC)"},
        {"q": "New Deal program created in 1935 that provides retirement income to Americans", "a": "Social Security"},
        {"q": "FDR's controversial plan to add more justices to the Supreme Court when it blocked New Deal legislation", "a": "Court-packing plan"},

        # ── POSTWAR AMERICA (1945–1960) ────────────────────────────────────────
        {"q": "Period of rapid suburban growth and baby boom after WWII, often called this", "a": "Postwar boom (or the Fifties)"},
        {"q": "GI Bill formally called the Servicemen's Readjustment Act provided veterans with education benefits and these", "a": "Low-cost mortgages (home loans)"},
        {"q": "Levittown was a prototype of this postwar phenomenon", "a": "Mass-produced suburbs"},
        {"q": "Post-WWII anxiety about communist infiltration was called this", "a": "Second Red Scare (McCarthyism)"},
        {"q": "Senator who led aggressive investigations into alleged communist infiltration of the US government", "a": "Joseph McCarthy"},
        {"q": "McCarthy's tactics of unfounded accusations gave the English language this word/phrase", "a": "McCarthyism"},
        {"q": "TV journalist whose on-air criticism helped bring McCarthy down", "a": "Edward R. Murrow"},
        {"q": "Husband and wife executed for allegedly passing atomic secrets to the Soviets", "a": "Julius and Ethel Rosenberg"},
        {"q": "Year the Rosenbergs were executed", "a": "1953"},
        {"q": "The House Un-American Activities Committee (HUAC) investigated Hollywood, resulting in these jailed writers and directors", "a": "Hollywood Ten"},
        {"q": "CIA-backed coup that overthrew Iran's elected leader Mosaddegh in 1953", "a": "Operation Ajax (Operation Boot)"},
        {"q": "CIA-backed invasion of Cuba in 1961 that failed disastrously", "a": "Bay of Pigs"},
        {"q": "Eisenhower's farewell address warned America about the growing power of this", "a": "Military-industrial complex"},
        {"q": "The Interstate Highway System, created in 1956, was officially named after this president", "a": "Dwight D. Eisenhower"},

        # ── CIVIL RIGHTS MOVEMENT ─────────────────────────────────────────────
        {"q": "1954 Supreme Court case that declared school segregation unconstitutional", "a": "Brown v. Board of Education"},
        {"q": "Chief Justice who wrote the unanimous Brown v. Board decision", "a": "Earl Warren"},
        {"q": "NAACP lawyer who argued Brown v. Board and later became the first Black Supreme Court justice", "a": "Thurgood Marshall"},
        {"q": "1955 Montgomery Bus Boycott was triggered by the arrest of this woman for refusing to give up her seat", "a": "Rosa Parks"},
        {"q": "The Montgomery Bus Boycott lasted this long", "a": "381 days"},
        {"q": "Young minister who led the Montgomery Bus Boycott and became the face of the civil rights movement", "a": "Martin Luther King Jr."},
        {"q": "MLK's philosophy of nonviolent resistance was inspired by this Indian leader's methods", "a": "Mahatma Gandhi"},
        {"q": "1960 sit-in at a Woolworth's lunch counter that sparked a wave of similar protests", "a": "Greensboro sit-in"},
        {"q": "City of the Greensboro sit-in", "a": "Greensboro, North Carolina"},
        {"q": "Student organization formed in 1960 to coordinate civil rights sit-ins and protests", "a": "Student Nonviolent Coordinating Committee (SNCC)"},
        {"q": "1961 interracial bus trips to challenge segregation on interstate buses were called these", "a": "Freedom Rides"},
        {"q": "University of Mississippi's integration crisis in 1962 involved the enrollment of this student", "a": "James Meredith"},
        {"q": "Civil rights leader murdered in Mississippi in 1963 whose killer was acquitted but later retried and convicted", "a": "Medgar Evers"},
        {"q": "MLK's 'Letter from Birmingham Jail' responded to criticism from these men", "a": "White moderate clergymen"},
        {"q": "1963 march where MLK delivered his 'I Have a Dream' speech", "a": "March on Washington"},
        {"q": "Number of people who attended the March on Washington in 1963", "a": "250,000"},
        {"q": "1964 law that banned discrimination based on race, color, religion, sex, or national origin", "a": "Civil Rights Act of 1964"},
        {"q": "1965 law that banned discriminatory voting practices including literacy tests and poll taxes", "a": "Voting Rights Act of 1965"},
        {"q": "1965 march from Selma to Montgomery was met with police violence on this bridge", "a": "Edmund Pettus Bridge"},
        {"q": "The 'Bloody Sunday' of the Selma march — date", "a": "March 7, 1965"},
        {"q": "MLK was assassinated in this city on April 4, 1968", "a": "Memphis, Tennessee"},
        {"q": "MLK was assassinated at this location in Memphis", "a": "Lorraine Motel"},
        {"q": "Man convicted of MLK's assassination", "a": "James Earl Ray"},
        {"q": "More militant civil rights organization that advocated Black Power and self-defense", "a": "Black Panther Party"},
        {"q": "Black Panther Party was founded in 1966 by these two men", "a": "Huey Newton and Bobby Seale"},
        {"q": "Malcolm X's philosophy differed from MLK's in advocating this", "a": "Black nationalism and self-defense (by any means necessary)"},
        {"q": "Malcolm X was a minister in this religious organization before breaking with it", "a": "Nation of Islam"},
        {"q": "Malcolm X was assassinated in this year", "a": "1965"},
        {"q": "Fair Housing Act of 1968 was signed one week after this event", "a": "MLK's assassination"},
        {"q": "The 24th Amendment of 1964 abolished this barrier to voting", "a": "Poll tax (in federal elections)"},

        # ── JFK ASSASSINATION & AFTERMATH ────────────────────────────────────
        {"q": "JFK was assassinated in this Texas city on November 22, 1963", "a": "Dallas"},
        {"q": "JFK's motorcade was traveling through this square when he was shot", "a": "Dealey Plaza"},
        {"q": "The commission that investigated JFK's assassination and concluded Oswald acted alone", "a": "Warren Commission"},
        {"q": "Chairman of the Warren Commission", "a": "Chief Justice Earl Warren"},
        {"q": "Jack Ruby shot and killed Lee Harvey Oswald while he was being transferred — where this occurred", "a": "Dallas Police headquarters"},
        {"q": "JFK's brother who was assassinated in 1968 while running for president", "a": "Robert F. Kennedy (RFK)"},
        {"q": "RFK was assassinated in this California city after winning the Democratic primary", "a": "Los Angeles (Ambassador Hotel)"},

        # ── GREAT SOCIETY & TURBULENT SIXTIES ────────────────────────────────
        {"q": "LBJ's domestic program that included Medicare, Medicaid, federal education funding, and voting rights", "a": "Great Society"},
        {"q": "Head Start, food stamps, and the Job Corps were all part of LBJ's", "a": "War on Poverty"},
        {"q": "The 1968 Democratic National Convention in Chicago was marred by this", "a": "Police riots against anti-war protesters"},
        {"q": "Governor who ordered the National Guard to shoot students at Kent State in 1970", "a": "James Rhodes"},
        {"q": "The women's liberation movement of the late 1960s was often called this", "a": "Second-wave feminism"},
        {"q": "Betty Friedan's 1963 book that helped spark second-wave feminism", "a": "The Feminine Mystique"},
        {"q": "The National Organization for Women (NOW) was founded in 1966 by this woman", "a": "Betty Friedan"},
        {"q": "1969 riots at this New York City bar launched the modern LGBTQ rights movement", "a": "Stonewall Inn"},
        {"q": "Woodstock music festival took place in this year", "a": "1969"},
        {"q": "Woodstock was held on a farm near this New York town", "a": "Bethel (near Woodstock)"},
        {"q": "The counterculture of the 1960s was centered in this San Francisco neighborhood", "a": "Haight-Ashbury"},

        # ── NIXON & WATERGATE ─────────────────────────────────────────────────
        {"q": "Nixon's strategy of appealing to Southern whites who resented civil rights legislation was called this", "a": "Southern Strategy"},
        {"q": "Nixon's policy of gradually withdrawing from Vietnam while building up South Vietnam's military", "a": "Vietnamization"},
        {"q": "Nixon's landmark foreign policy achievement in 1972", "a": "Opening diplomatic relations with China"},
        {"q": "Nixon's policy of reducing Cold War tensions with the Soviet Union", "a": "Détente"},
        {"q": "The Watergate scandal began with a break-in at this building in Washington", "a": "Watergate Hotel and Office Complex (DNC headquarters)"},
        {"q": "Date of the Watergate break-in", "a": "June 17, 1972"},
        {"q": "Nixon's cover-up involved paying hush money, destroying evidence, and firing the special prosecutor in this event", "a": "Saturday Night Massacre"},
        {"q": "Nixon fired Special Prosecutor Archibald Cox in the Saturday Night Massacre — how many DOJ officials resigned rather than carry out the order", "a": "Two (Attorney General Richardson and Deputy AG Ruckelshaus resigned; Bork fired Cox)"},
        {"q": "The Supreme Court ruled unanimously that Nixon must turn over these recordings", "a": "White House tape recordings"},
        {"q": "The 'smoking gun' tape proved Nixon had ordered this within days of the Watergate break-in", "a": "The cover-up (obstruction of justice)"},
        {"q": "Date Nixon resigned the presidency", "a": "August 9, 1974"},
        {"q": "Nixon's VP who resigned before him due to a separate scandal involving tax evasion", "a": "Spiro Agnew"},
        {"q": "Gerald Ford's controversial pardon of Nixon was given in this year", "a": "1974"},
        {"q": "The Watergate reporters who broke the story for the Washington Post", "a": "Bob Woodward and Carl Bernstein"},
        {"q": "Woodward and Bernstein's secret source, revealed decades later to be FBI's Mark Felt", "a": "Deep Throat"},

        # ── FORD, CARTER & REAGAN ─────────────────────────────────────────────
        {"q": "Economic phenomenon of the 1970s combining high inflation and high unemployment", "a": "Stagflation"},
        {"q": "1973 Arab oil embargo caused long lines at gas stations — triggered by US support for this country in the Yom Kippur War", "a": "Israel"},
        {"q": "Iranian hostage crisis began when students seized the US Embassy in Tehran in this year", "a": "1979"},
        {"q": "Number of Americans held hostage in Iran", "a": "52"},
        {"q": "Failed military operation to rescue the Iran hostages that ended in a helicopter crash in the desert", "a": "Operation Eagle Claw"},
        {"q": "The Iran hostages were released on the day this president was inaugurated", "a": "Ronald Reagan (January 20, 1981)"},
        {"q": "Reagan was nearly assassinated in 1981 by this man outside the Washington Hilton", "a": "John Hinckley Jr."},
        {"q": "Reagan's economic theory that tax cuts for the wealthy would 'trickle down' to everyone", "a": "Supply-side economics (Reaganomics / trickle-down economics)"},
        {"q": "Reagan fired these federal workers after they went on strike illegally in 1981", "a": "Air traffic controllers (PATCO)"},
        {"q": "Iran-Contra affair involved selling arms to Iran and using proceeds to fund rebels in this country", "a": "Nicaragua (the Contras)"},
        {"q": "National Security Council staffer at the center of the Iran-Contra affair", "a": "Oliver North"},
        {"q": "Reagan's famous Berlin Wall speech was delivered to this audience", "a": "The people of West Berlin (at the Brandenburg Gate)"},
        {"q": "AIDS epidemic began in the early 1980s — Reagan was criticized for not addressing it until this year", "a": "1987 (his first major speech on AIDS)"},

        # ── END OF COLD WAR & 1990S ────────────────────────────────────────────
        {"q": "Year the Berlin Wall fell", "a": "1989"},
        {"q": "Year the Soviet Union officially dissolved", "a": "1991"},
        {"q": "Last leader of the Soviet Union", "a": "Mikhail Gorbachev"},
        {"q": "Gorbachev's twin reform policies that opened the Soviet system", "a": "Glasnost (openness) and Perestroika (restructuring)"},
        {"q": "George H.W. Bush served as president when the Soviet Union collapsed and the Cold War ended — he called for a ___", "a": "New World Order"},
        {"q": "1992 Los Angeles riots were sparked by the acquittal of police officers who beat this man", "a": "Rodney King"},
        {"q": "Rodney King's famous plea during the riots", "a": "'Can we all get along?'"},
        {"q": "Bill Clinton's major domestic achievement that attempted to reform health care", "a": "Clinton health care plan (failed — led by Hillary Clinton)"},
        {"q": "1994 Republican revolution that gave the GOP control of Congress was organized around this document", "a": "Contract with America"},
        {"q": "Republican Speaker of the House who led the 1994 revolution", "a": "Newt Gingrich"},
        {"q": "The dot-com boom of the 1990s was centered in this California region", "a": "Silicon Valley"},
        {"q": "Domestic terrorist attack on April 19, 1995 that killed 168 people in Oklahoma City", "a": "Oklahoma City bombing"},
        {"q": "Man who carried out the Oklahoma City bombing", "a": "Timothy McVeigh"},
        {"q": "Clinton was impeached in 1998 — the two articles were perjury and this", "a": "Obstruction of justice"},
        {"q": "Clinton was acquitted by the Senate — the vote on perjury was this", "a": "45–55 (not guilty)"},
        {"q": "The disputed 2000 presidential election was decided by the Supreme Court in this case", "a": "Bush v. Gore"},
        {"q": "The disputed state in the 2000 election", "a": "Florida"},
        {"q": "The issue in Florida's 2000 recount that became a national punchline", "a": "Hanging chads (incompletely punched ballot cards)"},

        # ── POST-9/11 AMERICA ──────────────────────────────────────────────────
        {"q": "Date of the September 11, 2001 terrorist attacks", "a": "September 11, 2001"},
        {"q": "Four planes were hijacked on 9/11 — two hit the World Trade Center, one hit the Pentagon, and one crashed in this field", "a": "Shanksville, Pennsylvania (Flight 93)"},
        {"q": "Flight 93 passengers stormed the cockpit and crashed the plane to prevent it reaching its target — the passengers' rallying cry", "a": "'Let's roll' (Todd Beamer)"},
        {"q": "Terrorist organization responsible for the 9/11 attacks", "a": "Al-Qaeda"},
        {"q": "Leader of Al-Qaeda who planned the 9/11 attacks", "a": "Osama bin Laden"},
        {"q": "The USA PATRIOT Act of 2001 dramatically expanded the government's ability to do this", "a": "Conduct surveillance on American citizens"},
        {"q": "Department of Homeland Security was created in this year", "a": "2002"},
        {"q": "Osama bin Laden was killed by Navy SEALs in this year in this country", "a": "2011, in Abbottabad, Pakistan"},
        {"q": "Name of the Navy SEAL operation that killed bin Laden", "a": "Operation Neptune Spear"},
        {"q": "Hurricane Katrina devastated this city in August 2005", "a": "New Orleans"},
        {"q": "FEMA's response to Katrina was widely criticized — its director who resigned was this man", "a": "Michael Brown ('Brownie')"},
        {"q": "The 2008 financial crisis was triggered by the collapse of this type of securities", "a": "Mortgage-backed securities (subprime mortgage crisis)"},
        {"q": "Bush-era bank bailout program that injected $700 billion into the financial system", "a": "TARP (Troubled Asset Relief Program)"},
        {"q": "Investment bank whose collapse in 2008 triggered the financial crisis", "a": "Lehman Brothers"},

        # ── OBAMA ERA ─────────────────────────────────────────────────────────
        {"q": "Barack Obama became the first African American president, elected in this year", "a": "2008"},
        {"q": "Obama's 2010 health care reform law, commonly called this", "a": "Affordable Care Act (Obamacare)"},
        {"q": "The ACA's requirement that all Americans obtain health insurance was called this", "a": "Individual mandate"},
        {"q": "The economic stimulus package passed in 2009 to counter the recession was this amount", "a": "$787 billion (American Recovery and Reinvestment Act)"},
        {"q": "Obama's foreign policy reset with Cuba included restoring diplomatic relations in this year", "a": "2015"},
        {"q": "Supreme Court case that legalized same-sex marriage nationwide in 2015", "a": "Obergefell v. Hodges"},
        {"q": "The Arab Spring of 2011 led to regime changes in these countries (name two)", "a": "Tunisia, Egypt, Libya, Yemen (any two)"},
        {"q": "The Tea Party movement emerged in 2009 in opposition to Obama's", "a": "Stimulus spending and health care reform"},
        {"q": "The Occupy Wall Street movement of 2011 protested economic inequality using the slogan", "a": "'We are the 99%'"},

        # ── TRUMP & BIDEN ERA ─────────────────────────────────────────────────
        {"q": "Donald Trump's campaign slogan in 2016", "a": "Make America Great Again (MAGA)"},
        {"q": "Trump defeated this Democratic candidate in the 2016 election", "a": "Hillary Clinton"},
        {"q": "Trump's travel ban targeted citizens of these predominantly Muslim countries", "a": "Seven countries (Iran, Iraq, Libya, Somalia, Sudan, Syria, Yemen — list varied by version)"},
        {"q": "Trump was impeached twice — his first impeachment involved a phone call pressuring this country's president", "a": "Ukraine (Zelensky)"},
        {"q": "January 6, 2021 — supporters of Trump stormed this building", "a": "US Capitol"},
        {"q": "Trump's second impeachment charge was this", "a": "Incitement of insurrection"},
        {"q": "COVID-19 pandemic began spreading in the US in early this year", "a": "2020"},
        {"q": "US COVID-19 deaths exceeded this number", "a": "One million"},
        {"q": "The murder of George Floyd on May 25, 2020 sparked nationwide protests under this movement's banner", "a": "Black Lives Matter"},
        {"q": "George Floyd was killed by a Minneapolis police officer named this", "a": "Derek Chauvin"},
        {"q": "Derek Chauvin was convicted of murder in this year", "a": "2021"},
        {"q": "Biden's major climate and social spending bill passed in 2022 was called this", "a": "Inflation Reduction Act"},
        {"q": "The Supreme Court overturned Roe v. Wade in 2022 in this case", "a": "Dobbs v. Jackson Women's Health Organization"},
        {"q": "Roe v. Wade, the 1973 case overturned in 2022, established the constitutional right to this", "a": "Abortion"},

        # ── SOCIAL & CULTURAL MILESTONES ──────────────────────────────────────
        {"q": "Supreme Court case that established the right to contraception for married couples in 1965", "a": "Griswold v. Connecticut"},
        {"q": "1973 Supreme Court case that established abortion rights (later overturned)", "a": "Roe v. Wade"},
        {"q": "Title IX of the Education Amendments of 1972 prohibits sex discrimination in", "a": "Educational programs receiving federal funding (greatly expanded women's sports)"},
        {"q": "Americans with Disabilities Act was signed in this year by this president", "a": "1990, George H.W. Bush"},
        {"q": "Don't Ask Don't Tell, prohibiting openly gay service members, was repealed in this year", "a": "2011 (under Obama)"},
        {"q": "The #MeToo movement, which exposed widespread sexual harassment, went viral in this year", "a": "2017"},
        {"q": "Anita Hill testified against Supreme Court nominee Clarence Thomas in this year, alleging sexual harassment", "a": "1991"},
        {"q": "The first woman appointed to the Supreme Court", "a": "Sandra Day O'Connor (1981, by Reagan)"},
        {"q": "First Black woman appointed to the Supreme Court", "a": "Ketanji Brown Jackson (2022, by Biden)"},
        {"q": "The ERA — Equal Rights Amendment — was passed by Congress in 1972 but never ratified by enough states; it proposed equal rights based on this", "a": "Sex (gender)"},

        # ── TECHNOLOGY & ECONOMY ──────────────────────────────────────────────
        {"q": "The invention of the World Wide Web is credited to this British scientist in 1989", "a": "Tim Berners-Lee"},
        {"q": "Apple co-founder who introduced the iPhone in 2007", "a": "Steve Jobs"},
        {"q": "Social media platform founded by Mark Zuckerberg in 2004", "a": "Facebook (Meta)"},
        {"q": "The NAFTA trade agreement linking the US, Canada, and Mexico was signed in this year", "a": "1993 (took effect January 1, 1994)"},
        {"q": "The Great Recession of 2008–09 was the worst economic downturn since this earlier crisis", "a": "The Great Depression"},
        {"q": "Wall Street reform passed after the 2008 crisis to regulate banks and derivatives", "a": "Dodd-Frank Act (2010)"},
    ]
}
