"""
shakespeare_comedies_histories_deck.py
Shakespeare's comedies, histories, life, sonnets, language, and contemporaries.
Full Jeopardy depth — speeches, quotes, context, expressions.
"""

SHAKESPEARE_COMEDIES_HISTORIES_DECK = {
    "name": "Shakespeare: Comedies, Histories & Life",
    "icon": "📜",
    "description": "Comedies, history plays, sonnets, life, language, and Elizabethan context",
    "cards": [

        # ── SHAKESPEARE'S LIFE: BIRTH, DEATH & FAMILY ─────────────────────────
        {"q": "Shakespeare's birthplace", "a": "Stratford-upon-Avon, England"},
        {"q": "Shakespeare's birth year", "a": "1564"},
        {"q": "Shakespeare's death year", "a": "1616"},
        {"q": "Traditional date given for Shakespeare's birth AND death", "a": "April 23 (St. George's Day)"},
        {"q": "County of England where Stratford-upon-Avon is located", "a": "Warwickshire"},
        {"q": "Shakespeare was born the same year this Renaissance artist died", "a": "Michelangelo"},
        {"q": "Shakespeare's wife", "a": "Anne Hathaway"},
        {"q": "Shakespeare married Anne Hathaway when he was 18 — she was this age, making her notably older", "a": "26"},
        {"q": "Shakespeare and Anne Hathaway's first child", "a": "Susanna"},
        {"q": "Shakespeare and Anne Hathaway's twins, born 1585", "a": "Hamnet and Judith"},
        {"q": "Shakespeare's only son, who died at age 11 in 1596", "a": "Hamnet"},
        {"q": "Many scholars believe Shakespeare wrote Hamlet partly in grief for this person", "a": "His son Hamnet"},
        {"q": "Shakespeare's father's name and occupation", "a": "John Shakespeare — glovemaker, wool dealer, and local alderman"},
        {"q": "John Shakespeare rose to become this civic title in Stratford", "a": "High Bailiff (equivalent of mayor)"},
        {"q": "John Shakespeare later fell into debt and disgrace — one theory is that he was secretly this", "a": "Catholic (a recusant)"},
        {"q": "Shakespeare's mother's name and notable family connection", "a": "Mary Arden — from a prominent local gentry family"},
        {"q": "The school Shakespeare almost certainly attended in Stratford", "a": "King's New School (Stratford Grammar School)"},
        {"q": "Shakespeare's grammar school education would have consisted heavily of this language", "a": "Latin"},
        {"q": "The 'lost years' refer to the period from roughly 1585 to 1592 — this period is called that because", "a": "There are no historical records of Shakespeare's activities"},
        {"q": "Shakespeare's famous home in Stratford, the largest house in town, where he retired", "a": "New Place"},
        {"q": "New Place was purchased in 1597 — what this suggests about Shakespeare's finances", "a": "He had become wealthy from the theater"},
        {"q": "Shakespeare's will famously left Anne his 'second-best bed' — one interpretation is that this was actually", "a": "A term of affection (the best bed was kept for guests; the second-best was the marital bed)"},
        {"q": "Shakespeare's grave is in this church in Stratford", "a": "Holy Trinity Church"},
        {"q": "The curse carved on Shakespeare's gravestone warns against doing this", "a": "Moving his bones ('Cursed be he that moves my bones')"},
        {"q": "Shakespeare died at age", "a": "52"},

        # ── THE GLOBE & ELIZABETHAN THEATER ──────────────────────────────────
        {"q": "The theater most associated with Shakespeare", "a": "The Globe Theatre"},
        {"q": "Year the Globe Theatre was built", "a": "1599"},
        {"q": "Location of the Globe Theatre", "a": "Southwark, on the south bank of the Thames"},
        {"q": "The Globe was built partly using timber from this earlier Shoreditch theater", "a": "The Theatre"},
        {"q": "Shakespeare was a shareholder in this acting company that became the King's Men", "a": "Lord Chamberlain's Men"},
        {"q": "The Lord Chamberlain's Men were renamed the King's Men when this monarch became their patron", "a": "King James I (1603)"},
        {"q": "The Globe Theatre burned down during a performance of this play in 1613", "a": "Henry VIII (All Is True)"},
        {"q": "The Globe was rebuilt in 1614 — and rebuilt again in modern times near its original site, opening in this year", "a": "1997"},
        {"q": "Shakespeare's indoor winter theater was called this", "a": "Blackfriars Theatre"},
        {"q": "The three tiers of the Globe held this approximate number of spectators", "a": "3,000"},
        {"q": "Groundlings paid one penny to stand in this area", "a": "The pit (the yard)"},
        {"q": "Wealthier patrons sat in these covered areas of the Globe", "a": "The galleries"},
        {"q": "The Globe had no roof over the stage — performances happened in this kind of light", "a": "Daylight (afternoon performances)"},
        {"q": "Female roles in Shakespeare's time were played by these performers", "a": "Boy actors (women were barred from the stage)"},
        {"q": "The stage direction 'exit pursued by a bear' appears in this Shakespeare play", "a": "The Winter's Tale"},
        {"q": "This device at the Globe allowed actors to descend from above as gods or supernatural beings", "a": "The 'heavens' (a canopy with a trapdoor and flying machinery)"},
        {"q": "The trap door in the Globe's stage was used to represent this", "a": "Hell / the underworld"},

        # ── QUEEN ELIZABETH I & THE ELIZABETHAN AGE ───────────────────────────
        {"q": "The monarch under whom Shakespeare wrote the bulk of his plays", "a": "Queen Elizabeth I"},
        {"q": "Queen Elizabeth I's reign (years)", "a": "1558–1603"},
        {"q": "Elizabeth I's father who broke from the Catholic Church and founded the Church of England", "a": "Henry VIII"},
        {"q": "Elizabeth I was the daughter of Henry VIII and this mother, who was executed", "a": "Anne Boleyn"},
        {"q": "Elizabeth I never married — her nickname reflecting this", "a": "The Virgin Queen"},
        {"q": "Shakespeare's company performed at court for Elizabeth I multiple times — she reportedly especially loved this character", "a": "Falstaff"},
        {"q": "Elizabeth I died in 1603 and was succeeded by this king, who became Shakespeare's company's patron", "a": "James I (James VI of Scotland)"},
        {"q": "The period of Shakespeare's later career under James I is called the", "a": "Jacobean period"},
        {"q": "Shakespeare's play A Midsummer Night's Dream was likely written for performance at this type of event", "a": "A royal or aristocratic wedding"},
        {"q": "The Merry Wives of Windsor was reportedly written at Elizabeth I's request — she wanted to see", "a": "Falstaff in love"},
        {"q": "The Spanish Armada was defeated in 1588 — this event created a wave of national pride that fed into Shakespeare's", "a": "History plays (particularly the Henry plays celebrating English valor)"},
        {"q": "The Globe's flag signaled what type of play was being performed — a black flag meant this", "a": "A tragedy"},
        {"q": "A white flag at the Globe meant this type of play", "a": "A comedy"},
        {"q": "A red flag at the Globe meant this type of play", "a": "A history"},

        # ── FIRST FOLIO & PUBLICATION ─────────────────────────────────────────
        {"q": "The First Folio was published in this year, seven years after Shakespeare's death", "a": "1623"},
        {"q": "The First Folio was compiled by these two of Shakespeare's fellow actors", "a": "John Heminges and Henry Condell"},
        {"q": "Without the First Folio, these many Shakespeare plays would have been lost", "a": "18 (half his plays had never been printed before)"},
        {"q": "How many plays were included in the First Folio", "a": "36"},
        {"q": "Total plays now attributed to Shakespeare", "a": "37 (or 38, counting The Two Noble Kinsmen co-written with Fletcher)"},
        {"q": "Shakespeare's plays fall into these three main categories in the First Folio", "a": "Comedies, Histories, and Tragedies"},
        {"q": "During Shakespeare's lifetime, many of his plays were printed in these unauthorized cheap editions", "a": "Quartos (quarto editions)"},
        {"q": "The prefatory poem in the First Folio where Ben Jonson calls Shakespeare 'Soul of the Age'", "a": "'To the Memory of My Beloved, the Author'"},

        # ── CONTEMPORARIES & THE AUTHORSHIP QUESTION ──────────────────────────
        {"q": "Shakespeare's most famous contemporary playwright, sometimes proposed as the real author of his plays", "a": "Christopher Marlowe"},
        {"q": "Marlowe's most famous play about a scholar who sells his soul to the devil", "a": "Doctor Faustus"},
        {"q": "Marlowe's play featuring the line 'Was this the face that launched a thousand ships?' about Helen of Troy", "a": "Doctor Faustus"},
        {"q": "Marlowe wrote the first great English history play cycle — his plays about this king", "a": "Edward II (and Tamburlaine)"},
        {"q": "Marlowe died in 1593 in a tavern in Deptford — the official cause was this", "a": "A stabbing (allegedly a fight over a bill)"},
        {"q": "Some scholars believe Marlowe's death was actually connected to his work as this", "a": "A spy (government intelligence agent)"},
        {"q": "Ben Jonson's famous tribute: Shakespeare was 'not of an age, but for all ___'", "a": "Time"},
        {"q": "Ben Jonson also wrote that Shakespeare had 'small Latin and less ___'", "a": "Greek"},
        {"q": "Jonson's remark about Latin and Greek was meant as mild criticism but is now used to argue Shakespeare could not have written the plays because", "a": "They show deep classical knowledge"},
        {"q": "The most popular alternative candidate for authorship of Shakespeare's plays", "a": "Edward de Vere, 17th Earl of Oxford"},
        {"q": "The Oxfordian theory is complicated by the fact that de Vere died in 1604, but Shakespeare wrote plays until approximately", "a": "1613"},
        {"q": "John Webster, Shakespeare's contemporary, is best known for these two tragedies", "a": "The Duchess of Malfi and The White Devil"},
        {"q": "Thomas Kyd wrote this influential early revenge tragedy that directly influenced Hamlet", "a": "The Spanish Tragedy"},
        {"q": "The playwright who collaborated with Shakespeare on The Two Noble Kinsmen and Henry VIII", "a": "John Fletcher"},
        {"q": "Robert Greene, in 1592, attacked Shakespeare as an 'upstart crow' — this is the first known reference to Shakespeare as", "a": "A playwright in London"},

        # ── SONNETS ────────────────────────────────────────────────────────────
        {"q": "Number of Shakespeare's sonnets", "a": "154"},
        {"q": "Year Shakespeare's sonnets were first published", "a": "1609"},
        {"q": "The sonnets are dedicated to 'Mr. W.H.' — the two most debated candidates for his identity", "a": "Henry Wriothesley (Earl of Southampton) and William Herbert (Earl of Pembroke)"},
        {"q": "The 'Fair Youth' sonnets (1–126) are addressed to a young man — their emotional intensity has led to debate about Shakespeare's", "a": "Sexuality"},
        {"q": "The 'Dark Lady' sonnets (127–154) address a mysterious woman with dark hair and eyes — her identity is", "a": "Unknown"},
        {"q": "Sonnet 18 opens with this line", "a": "Shall I compare thee to a summer's day?"},
        {"q": "Sonnet 18's argument is that the beloved will live forever through this", "a": "The poem itself"},
        {"q": "Sonnet 18 ends: 'So long as men can breathe, or eyes can see / So long lives this, and this gives life to ___'", "a": "Thee"},
        {"q": "Sonnet 29 begins 'When, in disgrace with fortune and men's eyes' — its turn (volta) comes when the speaker thinks of this", "a": "His beloved (which lifts his spirits)"},
        {"q": "Sonnet 73 begins 'That time of year thou mayst in me behold' — the three metaphors used are autumn, twilight, and a dying ___", "a": "Fire (glowing embers)"},
        {"q": "Sonnet 116 defines love as something that 'is not love / Which alters when it alteration ___'", "a": "Finds"},
        {"q": "Sonnet 116's most famous line: 'Love is not love / Which alters when it alteration finds / Or bends with the remover to ___'", "a": "Remove"},
        {"q": "Sonnet 116 contains the phrase 'the marriage of true ___'", "a": "Minds"},
        {"q": "Sonnet 130 opens 'My mistress' eyes are nothing like the sun' — its purpose is to mock these", "a": "Conventional Petrarchan love sonnets that idealize women"},
        {"q": "Sonnet 130 ends by insisting the Dark Lady is 'as rare / As any she belied with ___'", "a": "False compare"},
        {"q": "Shakespeare's narrative poem dedicated to the Earl of Southampton, published 1593", "a": "Venus and Adonis"},
        {"q": "Shakespeare's darker narrative poem, published 1594, about a Roman noblewoman's rape and suicide", "a": "The Rape of Lucrece"},

        # ── HISTORY PLAYS: HENRY V ────────────────────────────────────────────
        {"q": "Shakespeare's history play about the English king who defeats France at Agincourt", "a": "Henry V"},
        {"q": "Henry V's famous speech before the Battle of Agincourt is called this", "a": "The St. Crispin's Day Speech"},
        {"q": "Henry V begins his Agincourt speech: 'Once more unto the breach, dear friends, once ___'", "a": "More"},
        {"q": "'Once more unto the breach' is from which play", "a": "Henry V"},
        {"q": "'We few, we happy few, we band of brothers' is from Henry V's speech on this day", "a": "St. Crispin's Day (the feast of Saints Crispin and Crispian)"},
        {"q": "The full 'band of brothers' line: 'We few, we happy few, we band of brothers; / For he today that sheds his blood with me / Shall be my ___'", "a": "Brother"},
        {"q": "Henry V declares that men who fight with him will 'hold their manhoods cheap' if they were not at this battle", "a": "Agincourt"},
        {"q": "The Chorus in Henry V opens each act with 'O for a Muse of ___'", "a": "Fire"},
        {"q": "Henry V disguises himself the night before Agincourt to walk among his troops — his disguised name", "a": "Harry le Roy (or simply a common soldier)"},
        {"q": "Henry V woos this French princess at the end of the play", "a": "Katherine (Catherine of Valois)"},
        {"q": "The historical Battle of Agincourt took place in this year", "a": "1415"},
        {"q": "Prince Hal's mentor and comic companion in Henry IV who is rejected in Henry V", "a": "Falstaff"},
        {"q": "Henry's rejection of Falstaff: 'I know thee not, old man. Fall to thy ___'", "a": "Prayers"},

        # ── HISTORY PLAYS: RICHARD III ────────────────────────────────────────
        {"q": "Richard III's famous opening soliloquy begins with this line", "a": "Now is the winter of our discontent"},
        {"q": "Richard III's opening soliloquy continues: 'Made glorious summer by this sun of ___'", "a": "York"},
        {"q": "Richard III describes himself as 'deformed, unfinished, sent before my time / Into this breathing world, scarce half made ___'", "a": "Up"},
        {"q": "Richard III says he is 'not shaped for sportive tricks / Nor made to court an amorous ___'", "a": "Looking glass"},
        {"q": "Richard III's despairing cry at the Battle of Bosworth: 'A horse! A horse! My kingdom for a ___'", "a": "Horse"},
        {"q": "Richard III's battle cry about a horse appears in this act", "a": "Act V"},
        {"q": "Richard III woos Lady Anne — notable because she is the widow of a man Richard himself ___", "a": "Killed"},
        {"q": "Richard III's opening soliloquy ends with his declaration that he will prove a ___", "a": "Villain"},

        # ── HISTORY PLAYS: RICHARD II, HENRY IV ───────────────────────────────
        {"q": "John of Gaunt's 'sceptred isle' speech praises England as 'This precious stone set in the silver ___'", "a": "Sea"},
        {"q": "John of Gaunt's speech is from this play", "a": "Richard II"},
        {"q": "John of Gaunt calls England 'this other Eden, demi-___'", "a": "Paradise"},
        {"q": "The full opening of the sceptred isle speech: 'This royal throne of kings, this sceptred isle / This earth of majesty, this seat of ___'", "a": "Mars"},
        {"q": "The tavern in London where Falstaff and Prince Hal spend time in Henry IV", "a": "The Boar's Head Tavern"},
        {"q": "Falstaff's famous speech arguing that honor is just a word — he says 'What is honour? A word. What is in that word, honour? Air.' — this is called his", "a": "Catechism on honour"},
        {"q": "In Henry IV Part 1, the rebel leader killed by Prince Hal at the Battle of Shrewsbury", "a": "Henry 'Hotspur' Percy"},
        {"q": "Hotspur's wife in Henry IV Part 1", "a": "Lady Percy (Kate)"},

        # ── COMEDIES: A MIDSUMMER NIGHT'S DREAM ──────────────────────────────
        {"q": "Shakespeare's comedy featuring Oberon, Titania, and Puck", "a": "A Midsummer Night's Dream"},
        {"q": "Puck's other name", "a": "Robin Goodfellow"},
        {"q": "The love potion in A Midsummer Night's Dream comes from the juice of this flower, also called Love-in-idleness", "a": "Pansy (wild pansy / heartsease)"},
        {"q": "Bottom is given a donkey's head — the fairy queen who falls in love with him", "a": "Titania"},
        {"q": "The four Athenian lovers in A Midsummer Night's Dream", "a": "Hermia, Lysander, Helena, and Demetrius"},
        {"q": "The mechanicals in A Midsummer Night's Dream are led by this weaver", "a": "Bottom"},
        {"q": "The play the mechanicals perform is called Pyramus and Thisbe — it parallels this other Shakespeare play", "a": "Romeo and Juliet"},
        {"q": "Puck's famous closing speech: 'If we shadows have offended, think but this, and all is ___'", "a": "Mended"},
        {"q": "Puck's speech offering that if the play has offended, they should think of it all as a ___", "a": "Dream"},
        {"q": "Oberon's description of where Titania sleeps: 'I know a bank where the wild thyme blows / Where oxlips and the nodding violet ___'", "a": "Grows"},
        {"q": "Titania's speech about the disordered seasons caused by her quarrel with Oberon illustrates this theme", "a": "Disorder in the fairy world causes disorder in nature"},

        # ── COMEDIES: AS YOU LIKE IT ──────────────────────────────────────────
        {"q": "The seven ages of man speech is spoken by Jaques and begins: 'All the world's a stage / And all the men and women merely ___'", "a": "Players"},
        {"q": "The seven ages of man in order", "a": "Infant, schoolboy, lover, soldier, justice, pantaloon, second childhood (sans everything)"},
        {"q": "The last age in Jaques' seven ages of man speech ends: 'Sans teeth, sans eyes, sans taste, sans ___'", "a": "Everything"},
        {"q": "Jaques' famous melancholy line: 'I can suck melancholy out of a song as a weasel sucks ___'", "a": "Eggs"},
        {"q": "Rosalind disguises herself as a boy named Ganymede — Ganymede was in mythology the cup-bearer to the ___", "a": "Gods (Zeus/Jupiter)"},
        {"q": "Touchstone is this type of character in As You Like It", "a": "A court jester / fool"},
        {"q": "'All the world's a stage' speech — the soldier's description includes 'seeking the bubble reputation / Even in the cannon's ___'", "a": "Mouth"},

        # ── COMEDIES: TWELFTH NIGHT ───────────────────────────────────────────
        {"q": "Twelfth Night opens with Duke Orsino's famous line about music and love", "a": "If music be the food of love, play on"},
        {"q": "Orsino's opening speech continues: 'Give me excess of it; that surfeiting / The appetite may sicken and so ___'", "a": "Die"},
        {"q": "Orsino says: 'If music be the food of love, play on / Give me excess of it, that surfeiting / The appetite may sicken and so die — / That strain again! It had a dying ___'", "a": "Fall"},
        {"q": "The play Twelfth Night is named after a holiday — what holiday", "a": "The twelfth night after Christmas (January 5, eve of Epiphany)"},
        {"q": "Malvolio reads a forged letter and believes Olivia loves him because it says 'Some are born great, some achieve greatness, and some have greatness ___'", "a": "Thrust upon them"},
        {"q": "The line 'Some are born great...' is now used proverbially to mean this", "a": "Greatness comes in different ways — through birth, effort, or circumstance"},
        {"q": "Feste the clown's role in Twelfth Night — unlike Malvolio, he has this quality", "a": "True wisdom beneath the foolishness"},
        {"q": "Sir Andrew Aguecheek is Sir Toby's foolish companion — his name is comic because 'ague' means this", "a": "A fever / illness (implying weakness)"},

        # ── COMEDIES: MUCH ADO ABOUT NOTHING ─────────────────────────────────
        {"q": "Beatrice's famous line refusing to marry: 'I had rather hear my dog bark at a crow than a man swear he ___'", "a": "Loves me"},
        {"q": "Benedick says of Beatrice: 'She speaks poniards, and every word stabs' — a poniard is this", "a": "A dagger"},
        {"q": "Benedick's speech about the ideal woman ends with his admission that he cannot find such a woman — 'till all graces be in one woman, one woman shall not come in my ___'", "a": "Grace"},
        {"q": "Dogberry's most famous malapropism: he tells the watch to 'comprehend all vagrom men' — he means this word", "a": "Apprehend"},
        {"q": "Much Ado takes place in this Italian location", "a": "Messina, Sicily"},

        # ── COMEDIES: THE TEMPEST ─────────────────────────────────────────────
        {"q": "Prospero's famous speech: 'Our revels now are ended. These our actors / As I foretold you, were all spirits and / Are melted into air, into thin ___'", "a": "Air"},
        {"q": "Prospero continues: 'We are such stuff / As dreams are made on, and our little life / Is rounded with a ___'", "a": "Sleep"},
        {"q": "Miranda's 'brave new world' speech: 'O, wonder! / How many goodly creatures are there here! / How beauteous mankind is! O brave new world / That has such people in't!' — Prospero's ironic response", "a": "'Tis new to thee"},
        {"q": "Caliban's speech about the island's sounds: 'Be not afeard; the isle is full of noises / Sounds and sweet airs that give delight and hurt not' — this speech shows Caliban has this quality", "a": "A poet's soul / sensitivity to beauty"},
        {"q": "Ariel's song: 'Full fathom five thy father lies / Of his bones are coral made / Those are pearls that were his eyes / Nothing of him that doth fade / But doth suffer a sea ___'", "a": "Change"},
        {"q": "Prospero's epilogue ends the play by asking the audience for this", "a": "Applause (to set him free)"},
        {"q": "The Tempest is set on an island — the island is sometimes identified as being near this location", "a": "The Mediterranean (or the New World / Bermuda — inspired by a shipwreck there)"},

        # ── COMEDIES: THE MERCHANT OF VENICE ─────────────────────────────────
        {"q": "Portia's full 'quality of mercy' speech begins: 'The quality of mercy is not strained / It droppeth as the gentle rain from heaven / Upon the place beneath. It is twice ___'", "a": "Blest"},
        {"q": "Portia continues: 'It is twice blest: / It blesseth him that gives and him that ___'", "a": "Takes"},
        {"q": "Portia says mercy 'is an attribute to God himself / And earthly power doth then show likest God's / When mercy seasons ___'", "a": "Justice"},
        {"q": "Shylock's 'Hath not a Jew eyes?' speech continues: '...fed with the same food, hurt with the same weapons, subject to the same diseases, healed by the same means, warmed and cooled by the same winter and summer as a ___?'", "a": "Christian"},
        {"q": "Shylock's speech ends: 'If you wrong us, shall we not revenge? If we are like you in the rest, we will ___'", "a": "Resemble you in that"},
        {"q": "The casket Bassanio correctly chooses is made of this metal", "a": "Lead"},
        {"q": "The inscription on the lead casket that wins Portia: 'Who chooseth me must give and hazard ___'", "a": "All he hath"},
        {"q": "Jessica steals Shylock's money and also this object, which Shylock laments losing even more — it was given to him by his dead wife", "a": "A turquoise ring"},

        # ── EXPRESSIONS COINED OR POPULARIZED BY SHAKESPEARE ─────────────────
        {"q": "'The green-eyed monster' for jealousy — from this play", "a": "Othello"},
        {"q": "'All that glitters is not gold' — from this play", "a": "The Merchant of Venice"},
        {"q": "'Break the ice' — from this play", "a": "The Taming of the Shrew"},
        {"q": "'Wild-goose chase' — from this play", "a": "Romeo and Juliet"},
        {"q": "'Vanish into thin air' — from this play", "a": "Othello"},
        {"q": "'Wear your heart on your sleeve' — from this play", "a": "Othello"},
        {"q": "'Good riddance' — from this play", "a": "Troilus and Cressida"},
        {"q": "'A foregone conclusion' — from this play", "a": "Othello"},
        {"q": "'Eaten out of house and home' — from this play", "a": "Henry IV Part 2"},
        {"q": "'Neither a borrower nor a lender be' — speaker and play", "a": "Polonius, in Hamlet"},
        {"q": "'Neither a borrower nor a lender be' comes just before this more famous line", "a": "'To thine own self be true'"},
        {"q": "'What's in a name?' — speaker and play", "a": "Juliet, in Romeo and Juliet"},
        {"q": "'Brevity is the soul of wit' — speaker and play", "a": "Polonius, in Hamlet (ironic, since Polonius is long-winded)"},
        {"q": "'All's well that ends well' — Shakespeare play with this title", "a": "All's Well That Ends Well"},
        {"q": "'The course of true love never did run smooth' — play", "a": "A Midsummer Night's Dream"},
        {"q": "'We know what we are, but know not what we may be' — speaker", "a": "Ophelia (in her madness), Hamlet"},
        {"q": "'Cowards die many times before their deaths; the valiant never taste of death but once' — speaker and play", "a": "Julius Caesar, in Julius Caesar"},
        {"q": "'This above all: to thine own self be true' — the irony of this line", "a": "It is spoken by Polonius, a hypocrite and manipulator"},
        {"q": "'There is nothing either good or bad but thinking makes it so' — speaker and play", "a": "Hamlet, in Hamlet"},
        {"q": "'All the world's a stage' — play", "a": "As You Like It"},
        {"q": "'Some are born great, some achieve greatness, and some have greatness thrust upon them' — play", "a": "Twelfth Night"},
        {"q": "'We are such stuff as dreams are made on' — play", "a": "The Tempest"},
        {"q": "'Now is the winter of our discontent' — play", "a": "Richard III"},
        {"q": "'Once more unto the breach' — play", "a": "Henry V"},
        {"q": "'Friends, Romans, countrymen, lend me your ears' — play", "a": "Julius Caesar"},
        {"q": "'To be or not to be' — play", "a": "Hamlet"},
        {"q": "'Et tu, Brute?' — play", "a": "Julius Caesar"},
        {"q": "'What light through yonder window breaks?' — speaker and play", "a": "Romeo, in Romeo and Juliet"},
        {"q": "'Double, double, toil and trouble' — play", "a": "Macbeth"},
        {"q": "'Tomorrow and tomorrow and tomorrow' — play", "a": "Macbeth"},
        {"q": "'Out, out, brief candle!' is part of this Macbeth soliloquy", "a": "'Tomorrow and tomorrow and tomorrow'"},
        {"q": "'The quality of mercy is not strained' — play", "a": "The Merchant of Venice"},
        {"q": "'If you prick us, do we not bleed?' — speaker and play", "a": "Shylock, in The Merchant of Venice"},
        {"q": "'A horse! A horse! My kingdom for a horse!' — play", "a": "Richard III"},
        {"q": "'Something is rotten in the state of Denmark' — speaker", "a": "Marcellus (not Hamlet), in Hamlet"},
        {"q": "'The lady doth protest too much, methinks' — speaker", "a": "Gertrude (not Hamlet), in Hamlet"},
        {"q": "'O, what a rogue and peasant slave am I!' — speaker", "a": "Hamlet (his second soliloquy)"},
        {"q": "'Cry 'Havoc!' and let slip the dogs of war' — speaker and play", "a": "Mark Antony, in Julius Caesar"},
    ]
}
