"""
shakespeare_tragedies_deck.py
Shakespeare's tragedies — deep Jeopardy coverage including full speech content,
character details, plot mechanics, and quotations line by line.
"""

SHAKESPEARE_TRAGEDIES_DECK = {
    "name": "Shakespeare: Tragedies",
    "icon": "💀",
    "description": "The tragedies — complete speech content, characters, plots, and famous quotations",
    "cards": [

        # ── HAMLET: THE 'TO BE OR NOT TO BE' SPEECH ───────────────────────────
        {"q": "Hamlet's 'To be, or not to be' soliloquy appears in this act and scene", "a": "Act III, Scene 1"},
        {"q": "Complete the opening: 'To be, or not to be — that is the ___'", "a": "Question"},
        {"q": "After 'that is the question,' Hamlet asks: 'Whether 'tis nobler in the mind to suffer / The slings and arrows of outrageous ___'", "a": "Fortune"},
        {"q": "The alternative Hamlet poses: 'Or to take arms against a sea of troubles / And by opposing ___'", "a": "End them"},
        {"q": "'To die, to sleep — / No more; and by a sleep to say we end / The heartache and the thousand natural shocks / That flesh is heir to: 'tis a consummation / Devoutly to be ___'", "a": "Wished"},
        {"q": "Hamlet's famous phrase about life's sufferings: 'the thousand natural shocks / That flesh is ___'", "a": "Heir to"},
        {"q": "Hamlet hesitates to commit suicide because of 'the dread of something after death — / The undiscovered country from whose bourn / No traveller ___'", "a": "Returns"},
        {"q": "The 'undiscovered country' in Hamlet's soliloquy refers to this", "a": "Death (the afterlife)"},
        {"q": "Hamlet refers to conscience as making us all ___", "a": "Cowards"},
        {"q": "The full phrase: 'Thus conscience does make cowards of us ___'", "a": "All"},
        {"q": "Hamlet says our 'native hue of resolution / Is sicklied o'er with the pale cast of ___'", "a": "Thought"},
        {"q": "'To shuffle off this mortal coil' — the word 'coil' in this context means", "a": "The turmoil / business of mortal life (not a spiral shape)"},
        {"q": "The phrase 'mortal coil' comes from this soliloquy", "a": "'To be, or not to be' (Hamlet, Act III)"},
        {"q": "Hamlet describes death as the possibility of dreaming — 'To sleep, perchance to dream — aye, there's the ___'", "a": "Rub"},
        {"q": "In the 'To be or not to be' speech, the word 'rub' means this", "a": "The obstacle / the difficulty (a term from lawn bowling)"},
        {"q": "Hamlet's soliloquy ends with him resolving that great undertakings 'lose the name of ___'", "a": "Action"},

        # ── HAMLET: OTHER SOLILOQUIES & SPEECHES ──────────────────────────────
        {"q": "Hamlet's first soliloquy begins: 'O, that this too, too solid flesh would melt / Thaw and resolve itself into a ___'", "a": "Dew"},
        {"q": "Hamlet's first soliloquy laments: 'How weary, stale, flat and unprofitable / Seem to me all the uses of this ___'", "a": "World"},
        {"q": "Hamlet compares the world to 'an unweeded garden / That grows to seed — things rank and gross in nature / Possess it merely.' This is his reaction to what event", "a": "His father's death and his mother's hasty remarriage"},
        {"q": "Hamlet's first soliloquy calls his mother's remarriage 'most wicked speed, to post / With such dexterity to incestuous ___'", "a": "Sheets"},
        {"q": "Hamlet's soliloquy 'O, what a rogue and peasant slave am I!' compares his inaction to the emotion displayed by a ___", "a": "Player (actor) weeping for Hecuba"},
        {"q": "Hamlet's third major soliloquy asks: 'Am I a coward? / Who calls me villain, breaks my pate across, / Plucks off my beard and blows it in my face?'  — this soliloquy ends with the plan to do what", "a": "Stage 'The Mousetrap' to catch Claudius's guilt"},
        {"q": "Hamlet's soliloquy while Claudius prays — Hamlet decides not to kill him because", "a": "Killing him while praying would send him to heaven"},
        {"q": "Hamlet's advice to the players includes: 'Suit the action to the word, the word to the ___'", "a": "Action"},
        {"q": "Hamlet tells the players: 'The purpose of playing...was and is to hold, as 'twere, the mirror up to ___'", "a": "Nature"},
        {"q": "Hamlet's famous line to Horatio: 'There are more things in heaven and earth, Horatio / Than are dreamt of in your ___'", "a": "Philosophy"},
        {"q": "Hamlet's last words before he dies", "a": "'The rest is silence'"},
        {"q": "Horatio's farewell to the dying Hamlet: 'Good night, sweet prince / And flights of angels sing thee to thy ___'", "a": "Rest"},
        {"q": "Hamlet says of his dead father: 'He was a man, take him for all in all / I shall not look upon his like ___'", "a": "Again"},

        # ── HAMLET: CHARACTERS & PLOT ─────────────────────────────────────────
        {"q": "Hamlet's treacherous uncle who murdered his father and married his mother", "a": "Claudius"},
        {"q": "Hamlet's mother who marries Claudius", "a": "Gertrude"},
        {"q": "Hamlet's love interest who goes mad and drowns", "a": "Ophelia"},
        {"q": "Ophelia's father, Polonius, is killed when Hamlet stabs through this in the Queen's bedroom", "a": "An arras (a tapestry/curtain)"},
        {"q": "Ophelia's brother who returns from France to avenge his father's death", "a": "Laertes"},
        {"q": "Hamlet's loyal friend who survives to tell the story", "a": "Horatio"},
        {"q": "How Hamlet's father was actually killed", "a": "Poison (hebenon) poured in his ear while he slept"},
        {"q": "'Alas, poor Yorick! I knew him, Horatio' — Yorick was the king's former ___", "a": "Jester"},
        {"q": "The play-within-a-play Hamlet arranges is called this", "a": "The Mousetrap"},
        {"q": "Hamlet's plan: 'The play's the thing / Wherein I'll catch the conscience of the ___'", "a": "King"},
        {"q": "Hamlet is sent to England with Rosencrantz and Guildenstern carrying a letter ordering his ___", "a": "Execution"},
        {"q": "Hamlet escapes death by rewriting the letter to order the execution of Rosencrantz and ___", "a": "Guildenstern"},
        {"q": "'Something is rotten in the state of Denmark' — this line is spoken by this character, not Hamlet", "a": "Marcellus"},
        {"q": "Polonius's famous advice: 'Neither a borrower nor a lender be' is followed by this more famous line", "a": "'This above all: to thine own self be true'"},
        {"q": "'To thine own self be true' is ironic because the speaker Polonius is this", "a": "A hypocrite, spy, and manipulator"},
        {"q": "The ghost of Hamlet's father first appears to these characters", "a": "The soldiers Bernardo, Francisco, and Horatio"},
        {"q": "Gertrude's description of Ophelia's drowning: she fell into the brook and 'her garments, heavy with their drink / Pulled the poor wretch from her melodious lay to muddy ___'", "a": "Death"},
        {"q": "Laertes' sword is poisoned in the final duel — who poisoned it", "a": "Claudius (in conspiracy with Laertes)"},
        {"q": "Gertrude dies by drinking the poisoned cup intended for ___", "a": "Hamlet"},
        {"q": "Four characters who die in Hamlet's final scene", "a": "Gertrude, Laertes, Claudius, and Hamlet"},
        {"q": "Hamlet's dying request to Horatio", "a": "To tell his story / 'Report me and my cause aright'"},

        # ── MACBETH: SPEECHES ─────────────────────────────────────────────────
        {"q": "The witches' opening incantation: 'Double, double, toil and trouble / Fire burn and cauldron ___'", "a": "Bubble"},
        {"q": "The witches' prophecy for Macbeth: 'All hail, Macbeth! hail to thee, Thane of ___'", "a": "Cawdor (and then King hereafter)"},
        {"q": "The witches tell Banquo he will be 'lesser than Macbeth, and greater' — and 'not so happy, yet much ___'", "a": "Happier"},
        {"q": "Macbeth's 'Is this a dagger' soliloquy: 'Is this a dagger which I see before me / The handle toward my hand? Come, let me clutch ___'", "a": "Thee"},
        {"q": "The dagger soliloquy ends with the bell that summons Macbeth to murder Duncan: 'Hear it not, Duncan; for it is a knell / That summons thee to heaven or to ___'", "a": "Hell"},
        {"q": "Lady Macbeth's 'unsex me here' speech asks the spirits to 'Stop up the access and passage to ___'", "a": "Remorse"},
        {"q": "Lady Macbeth's sleepwalking cry: 'Out, damned ___! Out, I say!'", "a": "Spot"},
        {"q": "Lady Macbeth says: 'Here's the smell of the blood still. All the perfumes of Arabia will not sweeten this little ___'", "a": "Hand"},
        {"q": "Macbeth's 'Tomorrow' soliloquy begins: 'Tomorrow, and tomorrow, and tomorrow / Creeps in this petty pace from day to day / To the last syllable of recorded ___'", "a": "Time"},
        {"q": "The 'Tomorrow' soliloquy continues: 'And all our yesterdays have lighted fools / The way to dusty ___'", "a": "Death"},
        {"q": "The soliloquy's most famous line: 'Out, out, brief ___!'", "a": "Candle"},
        {"q": "Macbeth describes life as 'a poor player / That struts and frets his hour upon the stage / And then is heard no ___'", "a": "More"},
        {"q": "Macbeth ends the 'Tomorrow' soliloquy calling life 'a tale / Told by an idiot, full of sound and fury / Signifying ___'", "a": "Nothing"},
        {"q": "Macbeth says 'I have supped full with horrors' — this phrase means", "a": "He has become so accustomed to horror that it no longer affects him"},
        {"q": "Macbeth's response to Lady Macbeth's death: 'She should have died hereafter / There would have been a time for such a ___'", "a": "Word"},
        {"q": "Macbeth says 'I have lived long enough. My way of life / Is fall'n into the sear, the yellow ___'", "a": "Leaf"},
        {"q": "Macbeth's desperate line just before his death: 'Yet I will try the last. Before my body / I throw my warlike shield. Lay on, Macduff / And damned be him that first cries, Hold, ___'", "a": "Enough"},

        # ── MACBETH: CHARACTERS & PLOT ────────────────────────────────────────
        {"q": "Macbeth's wife who urges him to murder King Duncan", "a": "Lady Macbeth"},
        {"q": "King of Scotland whom Macbeth murders to take the throne", "a": "Duncan"},
        {"q": "Duncan's son who flees to England after his father's murder", "a": "Malcolm"},
        {"q": "Macbeth's friend whose ghost haunts the banquet", "a": "Banquo"},
        {"q": "Macbeth hires murderers to kill Banquo — Banquo's son who escapes", "a": "Fleance"},
        {"q": "The Scottish nobleman whose family Macbeth has slaughtered, driving him to fight Macbeth", "a": "Macduff"},
        {"q": "Macduff kills Macbeth — why Macduff is not 'born of woman'", "a": "He was 'from his mother's womb untimely ripped' (Caesarean section)"},
        {"q": "The witches' equivocal prophecy about Birnam Wood coming to Dunsinane is fulfilled when Malcolm's soldiers do this", "a": "Cut branches from Birnam Wood to use as camouflage"},
        {"q": "The Scottish Play — superstition holds that saying 'Macbeth' in a theater causes this", "a": "Bad luck / disaster"},
        {"q": "Macbeth is set in which country", "a": "Scotland"},
        {"q": "King James I was particularly interested in Macbeth because of his interest in this subject and his claimed descent from Banquo", "a": "Witchcraft (he wrote 'Daemonologie')"},

        # ── KING LEAR ─────────────────────────────────────────────────────────
        {"q": "King Lear's three daughters, in order of age (oldest to youngest)", "a": "Goneril, Regan, Cordelia"},
        {"q": "Lear's test for his daughters: he will divide his kingdom based on which daughter loves him ___", "a": "Most"},
        {"q": "Cordelia's response to Lear's love test: she says she loves him 'According to my bond; no more, no ___'", "a": "Less"},
        {"q": "Lear's loyal advisor who defends Cordelia and is banished", "a": "The Earl of Kent"},
        {"q": "Gloucester's bastard son who manipulates his legitimate brother and their father", "a": "Edmund"},
        {"q": "Edmund's famous soliloquy celebrating illegitimacy begins: 'Thou, nature, art my goddess; to thy law / My services are ___'", "a": "Bound"},
        {"q": "Edmund says 'Why bastard? Wherefore base? / When my dimensions are as well compact / My mind as generous, and my shape as ___'", "a": "True"},
        {"q": "Edgar disguises himself as a mad beggar named this", "a": "Poor Tom"},
        {"q": "The Earl of Gloucester is blinded by Regan's husband — this character's name", "a": "Cornwall"},
        {"q": "Lear's speech in the storm begins: 'Blow, winds, and crack your cheeks! Rage! ___!'", "a": "Blow!"},
        {"q": "Lear on the heath cries: 'I am a man / More sinned against than ___'", "a": "Sinning"},
        {"q": "Lear's recognition of his own folly: 'I am old and foolish' — he says he is 'a very foolish, fond old ___'", "a": "Man"},
        {"q": "Cordelia is reunited with Lear — she says to him: 'And wast thou fain, poor father, / To hovel thee with swine and rogues forlorn / In short and musty ___?'", "a": "Straw"},
        {"q": "Cordelia is hanged in prison on the orders of this character", "a": "Edmund"},
        {"q": "Lear's anguished cry over the dead Cordelia: 'Howl, howl, howl, howl! O, you are men of stones! / Had I your tongues and eyes, I'd use them so / That heaven's vault should ___'", "a": "Crack"},
        {"q": "Lear's last lines over Cordelia: 'Do you see this? Look on her, look, her lips / Look there, look there!' — the ambiguity here is whether he thinks she is", "a": "Still alive (or is dying of grief believing this)"},
        {"q": "The sub-plot of King Lear involving Gloucester and his sons parallels the main plot in this way", "a": "Both involve a father deceived by a child he favored over a more honest one"},

        # ── OTHELLO ────────────────────────────────────────────────────────────
        {"q": "Othello's scheming, manipulative villain", "a": "Iago"},
        {"q": "Iago's stated motive for destroying Othello — two reasons he gives", "a": "He was passed over for lieutenant (given to Cassio) and suspects Othello slept with his wife Emilia"},
        {"q": "Iago's famous line about his own nature: 'I am not what ___'", "a": "I am"},
        {"q": "Iago says he will wear his heart upon his sleeve 'for daws to peck at. / I am not what I am.' — 'daws' are these birds", "a": "Jackdaws (foolish birds)"},
        {"q": "Othello's speech about his love for Desdemona: 'She loved me for the dangers I had passed / And I loved her that she did ___'", "a": "Pity them"},
        {"q": "Othello's speech after he kills Desdemona: 'I have done the state some service, and they know't. / No more of that. I pray you, in your letters / When you shall these unlucky deeds relate / Speak of me as I am; nothing extenuate / Nor set down aught in ___'", "a": "Malice"},
        {"q": "Othello describes himself in his final speech as 'one that loved not wisely but too ___'", "a": "Well"},
        {"q": "Othello's final speech: 'I kissed thee ere I killed thee: no way but this / Killing myself to die upon a ___'", "a": "Kiss"},
        {"q": "The handkerchief Iago plants to frame Desdemona — its significance to Othello", "a": "It was his first gift to her, given to him by his mother"},
        {"q": "Iago's wife Emilia steals the handkerchief — she gave it to Iago not knowing his plan. When she realizes, she exposes him and is immediately ___", "a": "Killed by Iago"},
        {"q": "Iago refuses to explain his motives at the end of the play, saying: 'Demand me nothing: what you know, you know / From this time forth I never will speak ___'", "a": "Word"},
        {"q": "Othello is set in Venice and then on this island, under threat from the Turks", "a": "Cyprus"},
        {"q": "Brabantio, Desdemona's father, accuses Othello of using witchcraft to win her — Othello's defense is that he wooed her only with his ___", "a": "Stories (tales of his adventures)"},
        {"q": "Cassio, Iago's rival, is disgraced when Iago gets him drunk and he does this", "a": "Fights and wounds Montano (the governor of Cyprus)"},

        # ── ROMEO AND JULIET ──────────────────────────────────────────────────
        {"q": "The Prologue calls Romeo and Juliet 'a pair of star-crossed lovers' and tells us they will 'take their life' — the prologue reveals the whole plot to do what", "a": "Focus attention on how, not what, will happen — on the inevitability of tragedy"},
        {"q": "The Prologue begins: 'Two households, both alike in dignity / In fair Verona, where we lay our ___'", "a": "Scene"},
        {"q": "The Prologue ends: 'The which if you with patient ears attend / What here shall miss, our toil shall strive to ___'", "a": "Mend"},
        {"q": "Romeo's first sight of Juliet — he says: 'Did my heart love till now? Forswear it, sight! / For I ne'er saw true beauty till this ___'", "a": "Night"},
        {"q": "Romeo says Juliet 'doth teach the torches to burn bright! / It seems she hangs upon the cheek of night / Like a rich jewel in an Ethiope's ___'", "a": "Ear"},
        {"q": "The balcony scene: Juliet says 'O Romeo, Romeo, wherefore art thou Romeo?' — 'wherefore' means this", "a": "Why (she asks why he must be a Montague, her enemy)"},
        {"q": "Juliet asks Romeo to 'Deny thy father and refuse thy name / Or if thou wilt not, be but sworn my love / And I'll no longer be a ___'", "a": "Capulet"},
        {"q": "Juliet's 'What's in a name?' speech: 'That which we call a rose / By any other name would smell as ___'", "a": "Sweet"},
        {"q": "Romeo's response to Juliet in the balcony scene: 'Call me but love, and I'll be new baptised / Henceforth I never will be ___'", "a": "Romeo"},
        {"q": "Juliet warns Romeo that their love is 'too rash, too sudden / Too like the lightning, which doth cease to be / Ere one can say it ___'", "a": "Lightens"},
        {"q": "Mercutio's famous description of Queen Mab: she is the fairies' midwife who rides in a 'chariot...drawn with a team of little ___'", "a": "Atomies (tiny creatures)"},
        {"q": "Mercutio's dying curse: 'A plague o' both your houses!' — he says this because he was killed by Tybalt, with Romeo ___", "a": "Getting in the way (trying to stop the fight)"},
        {"q": "After killing Tybalt, Romeo cries 'O, I am fortune's ___!'", "a": "Fool"},
        {"q": "Juliet's speech before taking the potion: 'What if this mixture do not work at all? / Shall I be married then tomorrow morning?' — she imagines waking in the tomb and going mad among the bones of her ancestors and the ghost of ___", "a": "Tybalt"},
        {"q": "Friar Lawrence's plan fails because the letter to Romeo explaining the fake death is not delivered — why", "a": "The messenger Friar John is quarantined due to plague"},
        {"q": "Romeo's last words before drinking the poison", "a": "'Thus with a kiss I die'"},
        {"q": "Juliet wakes, finds Romeo dead, and stabs herself with his dagger because 'O happy dagger! / This is thy sheath; there rust and let me ___'", "a": "Die"},
        {"q": "The Prince's closing couplet: 'For never was a story of more woe / Than this of Juliet and her ___'", "a": "Romeo"},
        {"q": "Prince Escalus rules Verona and appears at key moments to represent this force", "a": "Law and civil order"},

        # ── JULIUS CAESAR ─────────────────────────────────────────────────────
        {"q": "Mark Antony's funeral oration begins: 'Friends, Romans, countrymen, lend me your ears / I come to bury Caesar, not to ___'", "a": "Praise him"},
        {"q": "Antony's repeated refrain in the funeral speech: 'Brutus is an honourable ___'", "a": "Man"},
        {"q": "Antony says 'The evil that men do lives after them / The good is oft interred with their ___'", "a": "Bones"},
        {"q": "Antony shows the crowd Caesar's will and says Caesar left each Roman citizen this amount", "a": "75 drachmas"},
        {"q": "Antony points to each wound in Caesar's body, saving the most emotional moment — the wound made by ___", "a": "Brutus"},
        {"q": "Antony ends his speech saying the crowd should 'let slip the dogs of war' — the full line: 'Cry Havoc! and let slip the dogs of ___'", "a": "War"},
        {"q": "Brutus's speech to justify the assassination: 'Not that I loved Caesar less, but that I loved ___'", "a": "Rome more"},
        {"q": "Brutus argues Caesar was killed not because they loved him less but because 'had you rather Caesar were living and die all slaves, than that Caesar were dead to live all ___?'", "a": "Freemen"},
        {"q": "Cassius's argument to Brutus: 'The fault, dear Brutus, is not in our stars / But in ourselves, that we are ___'", "a": "Underlings"},
        {"q": "Cassius tells Brutus: 'Brutus and Caesar — what should be in that Caesar? / Why should that name be sounded more than ___?'", "a": "Yours"},
        {"q": "Caesar's famous line about Cassius: 'He thinks too much; such men are ___'", "a": "Dangerous"},
        {"q": "Caesar says he fears Cassius because 'he hath a lean and hungry look / He thinks too much: such men are dangerous' — Cassius's 'lean and hungry look' has become an idiom meaning", "a": "Ambition / dangerous scheming hunger for power"},
        {"q": "Caesar's wife Calpurnia begs him not to go to the Senate — she says 'the heavens themselves blaze forth the death of ___'", "a": "Princes"},
        {"q": "Decius Brutus (a conspirator) persuades Caesar to ignore Calpurnia's warning by reinterpreting the dream and suggesting the Senate will offer Caesar a ___", "a": "Crown"},
        {"q": "Caesar's last words in Shakespeare's play", "a": "'Et tu, Brute? Then fall, Caesar!'"},
        {"q": "After Caesar's death, Antony says 'O, pardon me, thou bleeding piece of earth / That I am meek and gentle with these ___'", "a": "Butchers"},
        {"q": "Cassius and Brutus both die by the sword at the Battle of ___", "a": "Philippi"},
        {"q": "Brutus asks his servant Strato to hold his sword so he can run upon it — Antony's epitaph for Brutus: 'This was the noblest Roman of ___'", "a": "Them all"},

        # ── ANTONY AND CLEOPATRA ──────────────────────────────────────────────
        {"q": "Enobarbus's famous description of Cleopatra on her barge: 'The barge she sat in, like a burnished throne / Burned on the water. The poop was beaten gold / Purple the sails, and so perfumed that / The winds were love-sick with ___'", "a": "Them"},
        {"q": "Enobarbus says of Cleopatra: 'Age cannot wither her, nor custom stale / Her infinite ___'", "a": "Variety"},
        {"q": "Antony says upon Cleopatra's death: 'I am dying, Egypt, dying' — the word 'Egypt' here means", "a": "Cleopatra herself (he addresses her as Egypt)"},
        {"q": "Cleopatra's speech before applying the asp: 'Give me my robe, put on my crown; I have / Immortal longings in ___'", "a": "Me"},
        {"q": "Cleopatra says 'I shall see / Some squeaking Cleopatra boy my greatness / I' the posture of a whore' — her fear is being taken to Rome and played in a theater by a ___", "a": "Boy (a boy actor playing a woman)"},
        {"q": "The play Antony and Cleopatra is a sequel of sorts to this earlier Shakespeare play", "a": "Julius Caesar"},

        # ── MERCHANT OF VENICE / PROBLEM PLAYS ───────────────────────────────
        {"q": "Portia's full 'quality of mercy' speech: 'It is twice blest / It blesseth him that gives and him that takes / 'Tis mightiest in the mightiest; it becomes / The thronèd monarch better than his ___'", "a": "Crown"},
        {"q": "Portia argues mercy 'is an attribute to God himself / And earthly power doth then show likest God's / When mercy seasons ___'", "a": "Justice"},
        {"q": "Shylock's 'Hath not a Jew eyes?' speech: 'If you prick us, do we not bleed? If you tickle us, do we not laugh? If you poison us, do we not die? And if you wrong us, shall we not ___?'", "a": "Revenge"},
        {"q": "Shylock's speech ends: 'The villainy you teach me I will execute, and it shall go hard but I will better the ___'", "a": "Instruction"},
        {"q": "In The Merchant of Venice, Antonio's ships have all sunk, and Shylock refuses mercy — Portia's legal argument that defeats him", "a": "He can have a pound of flesh but must shed no blood, and must cut exactly one pound — not more, not less"},
    ]
}
