"""
wwii_deck.py — World War II drill deck. Deep Jeopardy coverage.
"""

WWII_DECK = {
    "name": "World War II",
    "icon": "✈️",
    "description": "The Second World War — causes, major battles, leaders, the Holocaust, and aftermath",
    "cards": [

        # ── OVERVIEW & DATES ──────────────────────────────────────────────────
        {"q": "Years of World War II", "a": "1939–1945"},
        {"q": "Date WWII began in Europe (Germany invaded this country)", "a": "September 1, 1939 — Poland"},
        {"q": "Date WWII ended in Europe (V-E Day)", "a": "May 8, 1945"},
        {"q": "Date WWII ended in the Pacific (V-J Day)", "a": "August 15, 1945 (formally September 2, 1945)"},
        {"q": "The Allied Powers in WWII (main three)", "a": "United States, United Kingdom, and Soviet Union (the 'Big Three')"},
        {"q": "The Axis Powers in WWII", "a": "Germany, Italy, and Japan"},
        {"q": "Leaders of the Big Three Allied nations", "a": "FDR (US), Churchill (UK), Stalin (USSR)"},

        # ── CAUSES & RISE OF NAZISM ───────────────────────────────────────────
        {"q": "German leader who came to power in 1933 and launched WWII", "a": "Adolf Hitler"},
        {"q": "Hitler's political party", "a": "Nazi Party (National Socialist German Workers' Party)"},
        {"q": "Hitler's autobiography/manifesto outlining his ideology", "a": "Mein Kampf"},
        {"q": "Hitler's term for the German master race's need for living space in the East", "a": "Lebensraum"},
        {"q": "Hitler's annexation of Austria in 1938 was called this", "a": "Anschluss"},
        {"q": "1938 agreement where Britain and France allowed Germany to annex Czechoslovakia's Sudetenland", "a": "Munich Agreement"},
        {"q": "British PM who signed the Munich Agreement and declared 'peace for our time'", "a": "Neville Chamberlain"},
        {"q": "The policy of making concessions to an aggressor to avoid war is called this", "a": "Appeasement"},
        {"q": "Non-aggression pact between Germany and the Soviet Union signed in 1939", "a": "Molotov-Ribbentrop Pact"},
        {"q": "The Molotov-Ribbentrop Pact contained a secret protocol dividing Poland and Eastern Europe between Germany and ___", "a": "Soviet Union"},
        {"q": "1938 night of anti-Jewish violence across Germany and Austria, named for broken glass", "a": "Kristallnacht (Night of Broken Glass)"},

        # ── EUROPEAN THEATER ──────────────────────────────────────────────────
        {"q": "Germany's lightning-fast military strategy of combined armor and air power", "a": "Blitzkrieg (lightning war)"},
        {"q": "The period of inaction on the Western Front from fall 1939 to spring 1940", "a": "Phoney War"},
        {"q": "Evacuation of Allied troops from France in May–June 1940", "a": "Dunkirk (Operation Dynamo)"},
        {"q": "Number of Allied troops evacuated from Dunkirk", "a": "338,000"},
        {"q": "The air battle over Britain in summer 1940 that Germany lost", "a": "Battle of Britain"},
        {"q": "Churchill's famous quote about RAF pilots during the Battle of Britain: 'Never in the field of human conflict was so much owed by so many to so ___'", "a": "Few"},
        {"q": "German night bombing campaign against British cities in 1940–41", "a": "The Blitz"},
        {"q": "German invasion of the Soviet Union that began June 22, 1941", "a": "Operation Barbarossa"},
        {"q": "Operation Barbarossa was Hitler's biggest strategic blunder because it opened a ___-front war", "a": "Two"},
        {"q": "Brutal 5-month battle for a Soviet city in 1942–43, considered the turning point on the Eastern Front", "a": "Battle of Stalingrad"},
        {"q": "German general who surrendered at Stalingrad", "a": "Friedrich Paulus"},
        {"q": "Soviet general who defended Stalingrad", "a": "Georgy Zhukov"},
        {"q": "The siege of Leningrad lasted this long — the longest siege in modern history", "a": "872 days (nearly 2.5 years)"},
        {"q": "North African campaign battle where Britain defeated Rommel in 1942", "a": "Second Battle of El Alamein"},
        {"q": "German general known as the 'Desert Fox' who commanded North Africa", "a": "Erwin Rommel"},
        {"q": "British general who defeated Rommel at El Alamein", "a": "Bernard Montgomery"},
        {"q": "Allied invasion of North Africa in November 1942", "a": "Operation Torch"},
        {"q": "Allied invasion of Sicily and Italy beginning July 1943", "a": "Allied invasion of Italy (Operation Husky)"},
        {"q": "Italian leader who was deposed after the Allied invasion of Sicily", "a": "Benito Mussolini"},
        {"q": "D-Day — Allied invasion of Nazi-occupied France", "a": "June 6, 1944"},
        {"q": "Code name for the D-Day invasion", "a": "Operation Overlord"},
        {"q": "The five beaches of the D-Day landings", "a": "Utah, Omaha, Gold, Juno, and Sword"},
        {"q": "The bloodiest D-Day beach, where American troops suffered catastrophic casualties", "a": "Omaha Beach"},
        {"q": "Supreme Allied Commander who ordered the D-Day invasion", "a": "Dwight D. Eisenhower"},
        {"q": "German winter counteroffensive in December 1944 that created a 'bulge' in Allied lines", "a": "Battle of the Bulge"},
        {"q": "American general who defended Bastogne during the Battle of the Bulge", "a": "Anthony McAuliffe (who replied 'Nuts!' to German surrender demand)"},
        {"q": "McAuliffe's famous one-word reply to the German demand for surrender at Bastogne", "a": "Nuts!"},
        {"q": "American general who raced armor across France and relieved Bastogne", "a": "George S. Patton"},
        {"q": "Soviet-Allied conference in February 1945 that planned the postwar world", "a": "Yalta Conference"},
        {"q": "Location of the Yalta Conference", "a": "Yalta, Crimea (Soviet Union)"},
        {"q": "Hitler's death — manner and date", "a": "Suicide by gunshot, April 30, 1945, in his Berlin bunker"},

        # ── PACIFIC THEATER ───────────────────────────────────────────────────
        {"q": "Japanese attack that brought the US into WWII", "a": "Attack on Pearl Harbor"},
        {"q": "Date of the Pearl Harbor attack", "a": "December 7, 1941"},
        {"q": "FDR's description of December 7 in his address to Congress", "a": "'A date which will live in infamy'"},
        {"q": "American battleships sunk or damaged at Pearl Harbor", "a": "Eight battleships damaged or sunk (including USS Arizona)"},
        {"q": "US aircraft carriers that survived Pearl Harbor because they were at sea", "a": "USS Enterprise, USS Lexington, USS Saratoga"},
        {"q": "June 1942 naval battle considered the turning point of the Pacific War", "a": "Battle of Midway"},
        {"q": "At Midway, the US sank four Japanese aircraft carriers after decoding this", "a": "Japanese naval codes (JN-25)"},
        {"q": "American admiral who commanded at Midway", "a": "Chester Nimitz (overall); Raymond Spruance (Task Force 16)"},
        {"q": "Japanese admiral who commanded at Midway", "a": "Isoroku Yamamoto"},
        {"q": "Island-hopping strategy in the Pacific sought to capture strategic islands while bypassing these", "a": "Heavily fortified Japanese positions"},
        {"q": "Brutal August 1942–February 1943 Pacific campaign for a key airfield", "a": "Guadalcanal"},
        {"q": "February 1945 battle for a volcanic Pacific island, site of the famous flag-raising photo", "a": "Battle of Iwo Jima"},
        {"q": "Photographer who took the iconic Iwo Jima flag-raising photo", "a": "Joe Rosenthal"},
        {"q": "The April–June 1945 battle for the largest Ryukyu island was the last major Pacific battle", "a": "Battle of Okinawa"},
        {"q": "Japanese suicide pilots who crashed their planes into Allied ships", "a": "Kamikaze pilots"},
        {"q": "Code name for the atomic bomb project", "a": "Manhattan Project"},
        {"q": "Scientific director of the Manhattan Project", "a": "J. Robert Oppenheimer"},
        {"q": "Military director of the Manhattan Project", "a": "General Leslie Groves"},
        {"q": "Location where the first atomic bomb was tested in July 1945", "a": "Trinity test site, New Mexico"},
        {"q": "First city hit by an atomic bomb, August 6, 1945", "a": "Hiroshima"},
        {"q": "Second city hit by an atomic bomb, August 9, 1945", "a": "Nagasaki"},
        {"q": "Name of the plane that dropped the bomb on Hiroshima", "a": "Enola Gay"},
        {"q": "Pilot of the Enola Gay", "a": "Paul Tibbets"},
        {"q": "Code names of the two atomic bombs dropped on Japan", "a": "Little Boy (Hiroshima) and Fat Man (Nagasaki)"},
        {"q": "Approximate combined death toll of Hiroshima and Nagasaki bombings", "a": "130,000–226,000"},
        {"q": "Japanese Emperor who announced Japan's surrender", "a": "Emperor Hirohito"},
        {"q": "Japan formally surrendered aboard this US battleship in Tokyo Bay", "a": "USS Missouri"},

        # ── THE HOLOCAUST ─────────────────────────────────────────────────────
        {"q": "Nazi genocide that systematically murdered approximately 6 million Jewish people", "a": "The Holocaust"},
        {"q": "The Nazi plan to exterminate all European Jews was called this", "a": "Final Solution (Endlösung)"},
        {"q": "1942 meeting where Nazi leaders coordinated the Final Solution", "a": "Wannsee Conference"},
        {"q": "Largest Nazi death camp, where an estimated 1.1 million people were killed", "a": "Auschwitz-Birkenau"},
        {"q": "Location of Auschwitz", "a": "Occupied Poland"},
        {"q": "Nazi laws of 1935 that stripped German Jews of citizenship and civil rights", "a": "Nuremberg Laws"},
        {"q": "Diarist who hid with her family in Amsterdam and was eventually caught and killed", "a": "Anne Frank"},
        {"q": "Anne Frank's diary was published posthumously by her father, the only family member to survive, named ___", "a": "Otto Frank"},
        {"q": "German industrialist who saved over 1,000 Jewish workers by employing them in his factories", "a": "Oskar Schindler"},
        {"q": "Swedish diplomat who saved tens of thousands of Hungarian Jews by issuing protective passports", "a": "Raoul Wallenberg"},
        {"q": "Approximate total number of Holocaust victims including Jews, Roma, disabled, and others", "a": "11–17 million"},
        {"q": "Postwar trials that prosecuted Nazi war criminals for crimes against humanity", "a": "Nuremberg Trials"},
        {"q": "Location of the postwar Nazi war crimes trials", "a": "Nuremberg, Germany"},
        {"q": "Nazi official found guilty of the Final Solution at Nuremberg; 'banality of evil'", "a": "Adolf Eichmann (tried later in Israel; the 'banality of evil' concept came from Hannah Arendt)"},
        {"q": "Hitler's deputy who escaped to Argentina; captured and tried in Israel in 1961", "a": "Adolf Eichmann"},

        # ── LEADERS ───────────────────────────────────────────────────────────
        {"q": "British Prime Minister for most of WWII", "a": "Winston Churchill"},
        {"q": "Churchill replaced this prime minister in May 1940", "a": "Neville Chamberlain"},
        {"q": "Churchill's defiant speech after Dunkirk: 'We shall fight on the beaches... we shall never ___'", "a": "Surrender"},
        {"q": "Leader of Free France who rallied French resistance from London", "a": "Charles de Gaulle"},
        {"q": "Italian dictator executed by partisans in April 1945", "a": "Benito Mussolini"},
        {"q": "Mussolini's title as Italian fascist leader", "a": "Il Duce (The Leader)"},
        {"q": "Hitler's title as Nazi leader", "a": "Der Führer (The Leader)"},
        {"q": "Japanese military leader who planned Pearl Harbor and served as PM for much of the war", "a": "Hideki Tojo"},
        {"q": "American general who commanded Allied forces in the Pacific and accepted Japan's surrender", "a": "Douglas MacArthur"},
        {"q": "MacArthur's famous vow upon leaving the Philippines in 1942", "a": "I shall return"},
        {"q": "US admiral known as 'Bull' who commanded the Pacific Fleet after Nimitz", "a": "William 'Bull' Halsey"},
        {"q": "Soviet foreign minister who negotiated the Molotov-Ribbentrop Pact", "a": "Vyacheslav Molotov"},
        {"q": "US general known as 'Old Blood and Guts' who commanded the Third Army", "a": "George S. Patton"},
        {"q": "Patton was temporarily relieved of command after this incident", "a": "Slapping a shell-shocked soldier"},

        # ── HOME FRONT & SOCIETY ──────────────────────────────────────────────
        {"q": "Name for the symbolic American woman worker used in wartime propaganda", "a": "Rosie the Riveter"},
        {"q": "Executive Order 9066 authorized the forced relocation of Japanese Americans to these", "a": "Internment camps"},
        {"q": "President who signed Executive Order 9066", "a": "Franklin D. Roosevelt"},
        {"q": "Approximate number of Japanese Americans forcibly interned during WWII", "a": "120,000"},
        {"q": "US law that provided veterans with education benefits and home loans after WWII", "a": "GI Bill (Servicemen's Readjustment Act of 1944)"},
        {"q": "WWII-era term for soldiers of the US military", "a": "GIs (Government Issue)"},
        {"q": "Wartime rationing in the US included these two items (among many)", "a": "Gasoline, rubber, sugar, meat (any two)"},
        {"q": "The Lend-Lease Act allowed the US to supply Allies before entering the war, signed by FDR in", "a": "1941"},

        # ── AFTERMATH ─────────────────────────────────────────────────────────
        {"q": "International organization created after WWII to replace the failed League of Nations", "a": "United Nations"},
        {"q": "Year the United Nations was founded", "a": "1945"},
        {"q": "US plan to rebuild Western European economies after WWII", "a": "Marshall Plan (European Recovery Program)"},
        {"q": "Named after this Secretary of State", "a": "George Marshall"},
        {"q": "Division of Germany into occupation zones after WWII eventually created these two countries", "a": "West Germany and East Germany"},
        {"q": "The Iron Curtain speech that marked the beginning of the Cold War was delivered by this man", "a": "Winston Churchill (1946, in Fulton, Missouri)"},
        {"q": "The postwar trial format created at Nuremberg established international law against these", "a": "Crimes against humanity, war crimes, and crimes against peace"},
        {"q": "Approximate total WWII deaths (military and civilian combined)", "a": "70–85 million"},
        {"q": "WWII generation who came of age during the Depression and fought WWII was called this by Tom Brokaw", "a": "Greatest Generation"},
    ]
}
